{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "name": "nematodes FNN.ipynb",
      "provenance": [],
      "authorship_tag": "ABX9TyMAR2fhWqAsV7g9jOafGDM6",
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/niuhaoyu16/nematodes_detection_using_walabot/blob/main/nematodes_FNN.ipynb\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "bRWGt4awASnw"
      },
      "source": [
        "from sklearn.ensemble import RandomForestClassifier\n",
        "from sklearn.ensemble import VotingClassifier\n",
        "from sklearn.linear_model import LogisticRegression\n",
        "from sklearn.svm import SVC\n",
        "from sklearn.model_selection import train_test_split\n",
        "import matplotlib.pyplot as plt\n",
        "from scipy import io\n",
        "import numpy as np\n",
        "import pandas as pd\n",
        "import matplotlib as mpl\n",
        "%tensorflow_version 1.x\n",
        "mpl.rc('axes', labelsize=16)\n",
        "mpl.rc('xtick', labelsize=14)\n",
        "mpl.rc('ytick', labelsize=14)"
      ],
      "execution_count": 43,
      "outputs": []
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "srFv4_CyAVwV"
      },
      "source": [
        "dataset= io.loadmat('levels.mat')\n",
        "labels = io.loadmat('y.mat')\n",
        "X = dataset['X']\n",
        "y = labels['y'].astype(np.int32)-1"
      ],
      "execution_count": 44,
      "outputs": []
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "tRujULl_AbK8"
      },
      "source": [
        "X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)"
      ],
      "execution_count": 45,
      "outputs": []
    },
    {
      "cell_type": "code",
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "flkU_UpeBdDa",
        "outputId": "0b019c16-b47d-4a50-f3c5-6065ee18475c"
      },
      "source": [
        "import tensorflow as tf\n",
        "X_train.shape"
      ],
      "execution_count": 56,
      "outputs": [
        {
          "output_type": "execute_result",
          "data": {
            "text/plain": [
              "(60, 2048)"
            ]
          },
          "metadata": {
            "tags": []
          },
          "execution_count": 56
        }
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "sFLtJjriAc_5"
      },
      "source": [
        "k_range = range(1,100,1)\n",
        "models_per_k = []\n",
        "for k in k_range:\n",
        "  print(\"k={}\".format(k))\n",
        "  feature_cols = [tf.feature_column.numeric_column(\"X\", shape=[64 * 32])]\n",
        "  dnn_clf = tf.estimator.DNNClassifier(hidden_units=[300,100], n_classes=4,\n",
        "                                     feature_columns=feature_cols)\n",
        "\n",
        "  input_fn = tf.estimator.inputs.numpy_input_fn(\n",
        "    x={\"X\": X_train}, y=y_train, num_epochs=200, batch_size=10, shuffle=True)\n",
        "\n",
        "\n",
        "  kmeans= dnn_clf.train(input_fn=input_fn)\n",
        "  models_per_k.append(kmeans)"
      ],
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "code",
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 1000
        },
        "id": "ckniQkhIEphu",
        "outputId": "04104c63-c448-42a8-de92-dfd7406b5574"
      },
      "source": [
        "\n",
        "accuracy_scores = [model.evaluate(input_fn=test_input_fn)['accuracy']\n",
        "                      for model in models_per_k]\n",
        "best_index = np.argmax(accuracy_scores)\n",
        "best_k = k_range[best_index]\n",
        "best_score = accuracy_scores[best_index]\n",
        "\n",
        "plt.figure(figsize=(8, 3))\n",
        "plt.plot(k_range, accuracy_scores, \"bo-\")\n",
        "plt.xlabel(\"$k$\", fontsize=14)\n",
        "plt.ylabel(\"accuracy score\", fontsize=14)\n",
        "plt.plot(best_k, best_score, \"rs\")\n",
        "plt.show()"
      ],
      "execution_count": 48,
      "outputs": [
        {
          "output_type": "stream",
          "text": [
            "INFO:tensorflow:Calling model_fn.\n",
            "WARNING:tensorflow:Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x7f6290e6d978>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Num'\n",
            "WARNING: Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x7f6290e6d978>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Num'\n",
            "INFO:tensorflow:Done calling model_fn.\n",
            "INFO:tensorflow:Starting evaluation at 2021-02-08T20:32:47Z\n",
            "INFO:tensorflow:Graph was finalized.\n",
            "INFO:tensorflow:Restoring parameters from /tmp/tmpffx68bpz/model.ckpt-1200\n",
            "INFO:tensorflow:Running local_init_op.\n",
            "INFO:tensorflow:Done running local_init_op.\n",
            "INFO:tensorflow:Finished evaluation at 2021-02-08-20:32:47\n",
            "INFO:tensorflow:Saving dict for global step 1200: accuracy = 0.8095238, average_loss = 0.96077967, global_step = 1200, loss = 20.176373\n",
            "INFO:tensorflow:Saving 'checkpoint_path' summary for global step 1200: /tmp/tmpffx68bpz/model.ckpt-1200\n",
            "INFO:tensorflow:Calling model_fn.\n",
            "WARNING:tensorflow:Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x7f6292d24710>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Num'\n",
            "WARNING: Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x7f6292d24710>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Num'\n",
            "INFO:tensorflow:Done calling model_fn.\n",
            "INFO:tensorflow:Starting evaluation at 2021-02-08T20:32:48Z\n",
            "INFO:tensorflow:Graph was finalized.\n",
            "INFO:tensorflow:Restoring parameters from /tmp/tmpx36u4cp7/model.ckpt-1200\n",
            "INFO:tensorflow:Running local_init_op.\n",
            "INFO:tensorflow:Done running local_init_op.\n",
            "INFO:tensorflow:Finished evaluation at 2021-02-08-20:32:48\n",
            "INFO:tensorflow:Saving dict for global step 1200: accuracy = 0.85714287, average_loss = 0.5660142, global_step = 1200, loss = 11.886298\n",
            "INFO:tensorflow:Saving 'checkpoint_path' summary for global step 1200: /tmp/tmpx36u4cp7/model.ckpt-1200\n",
            "INFO:tensorflow:Calling model_fn.\n",
            "WARNING:tensorflow:Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x7f628b33e160>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Num'\n",
            "WARNING: Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x7f628b33e160>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Num'\n",
            "INFO:tensorflow:Done calling model_fn.\n",
            "INFO:tensorflow:Starting evaluation at 2021-02-08T20:32:48Z\n",
            "INFO:tensorflow:Graph was finalized.\n",
            "INFO:tensorflow:Restoring parameters from /tmp/tmpydu3ojxj/model.ckpt-1200\n",
            "INFO:tensorflow:Running local_init_op.\n",
            "INFO:tensorflow:Done running local_init_op.\n",
            "INFO:tensorflow:Finished evaluation at 2021-02-08-20:32:49\n",
            "INFO:tensorflow:Saving dict for global step 1200: accuracy = 0.9047619, average_loss = 0.46061465, global_step = 1200, loss = 9.672908\n",
            "INFO:tensorflow:Saving 'checkpoint_path' summary for global step 1200: /tmp/tmpydu3ojxj/model.ckpt-1200\n",
            "INFO:tensorflow:Calling model_fn.\n",
            "WARNING:tensorflow:Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x7f6298456a90>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Num'\n",
            "WARNING: Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x7f6298456a90>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Num'\n",
            "INFO:tensorflow:Done calling model_fn.\n",
            "INFO:tensorflow:Starting evaluation at 2021-02-08T20:32:49Z\n",
            "INFO:tensorflow:Graph was finalized.\n",
            "INFO:tensorflow:Restoring parameters from /tmp/tmpb7heds8s/model.ckpt-1200\n",
            "INFO:tensorflow:Running local_init_op.\n",
            "INFO:tensorflow:Done running local_init_op.\n",
            "INFO:tensorflow:Finished evaluation at 2021-02-08-20:32:50\n",
            "INFO:tensorflow:Saving dict for global step 1200: accuracy = 0.8095238, average_loss = 0.75774884, global_step = 1200, loss = 15.912725\n",
            "INFO:tensorflow:Saving 'checkpoint_path' summary for global step 1200: /tmp/tmpb7heds8s/model.ckpt-1200\n",
            "INFO:tensorflow:Calling model_fn.\n",
            "WARNING:tensorflow:Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x7f62934e0278>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Num'\n",
            "WARNING: Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x7f62934e0278>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Num'\n",
            "INFO:tensorflow:Done calling model_fn.\n",
            "INFO:tensorflow:Starting evaluation at 2021-02-08T20:32:50Z\n",
            "INFO:tensorflow:Graph was finalized.\n",
            "INFO:tensorflow:Restoring parameters from /tmp/tmprlrc2zjq/model.ckpt-1200\n",
            "INFO:tensorflow:Running local_init_op.\n",
            "INFO:tensorflow:Done running local_init_op.\n",
            "INFO:tensorflow:Finished evaluation at 2021-02-08-20:32:50\n",
            "INFO:tensorflow:Saving dict for global step 1200: accuracy = 0.7619048, average_loss = 0.5333302, global_step = 1200, loss = 11.199934\n",
            "INFO:tensorflow:Saving 'checkpoint_path' summary for global step 1200: /tmp/tmprlrc2zjq/model.ckpt-1200\n",
            "INFO:tensorflow:Calling model_fn.\n",
            "WARNING:tensorflow:Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x7f6292bf9470>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Num'\n",
            "WARNING: Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x7f6292bf9470>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Num'\n",
            "INFO:tensorflow:Done calling model_fn.\n",
            "INFO:tensorflow:Starting evaluation at 2021-02-08T20:32:51Z\n",
            "INFO:tensorflow:Graph was finalized.\n",
            "INFO:tensorflow:Restoring parameters from /tmp/tmplr9ik_sg/model.ckpt-1200\n",
            "INFO:tensorflow:Running local_init_op.\n",
            "INFO:tensorflow:Done running local_init_op.\n",
            "INFO:tensorflow:Finished evaluation at 2021-02-08-20:32:51\n",
            "INFO:tensorflow:Saving dict for global step 1200: accuracy = 0.85714287, average_loss = 0.41189075, global_step = 1200, loss = 8.649706\n",
            "INFO:tensorflow:Saving 'checkpoint_path' summary for global step 1200: /tmp/tmplr9ik_sg/model.ckpt-1200\n",
            "INFO:tensorflow:Calling model_fn.\n",
            "WARNING:tensorflow:Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x7f6293359d30>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Num'\n",
            "WARNING: Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x7f6293359d30>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Num'\n",
            "INFO:tensorflow:Done calling model_fn.\n",
            "INFO:tensorflow:Starting evaluation at 2021-02-08T20:32:52Z\n",
            "INFO:tensorflow:Graph was finalized.\n",
            "INFO:tensorflow:Restoring parameters from /tmp/tmp2lcfgko9/model.ckpt-1200\n",
            "INFO:tensorflow:Running local_init_op.\n",
            "INFO:tensorflow:Done running local_init_op.\n",
            "INFO:tensorflow:Finished evaluation at 2021-02-08-20:32:52\n",
            "INFO:tensorflow:Saving dict for global step 1200: accuracy = 0.61904764, average_loss = 0.75175977, global_step = 1200, loss = 15.786955\n",
            "INFO:tensorflow:Saving 'checkpoint_path' summary for global step 1200: /tmp/tmp2lcfgko9/model.ckpt-1200\n",
            "INFO:tensorflow:Calling model_fn.\n",
            "WARNING:tensorflow:Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x7f629135fe48>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Num'\n",
            "WARNING: Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x7f629135fe48>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Num'\n",
            "INFO:tensorflow:Done calling model_fn.\n",
            "INFO:tensorflow:Starting evaluation at 2021-02-08T20:32:52Z\n",
            "INFO:tensorflow:Graph was finalized.\n",
            "INFO:tensorflow:Restoring parameters from /tmp/tmp5k_alarh/model.ckpt-1200\n",
            "INFO:tensorflow:Running local_init_op.\n",
            "INFO:tensorflow:Done running local_init_op.\n",
            "INFO:tensorflow:Finished evaluation at 2021-02-08-20:32:53\n",
            "INFO:tensorflow:Saving dict for global step 1200: accuracy = 0.8095238, average_loss = 0.4248754, global_step = 1200, loss = 8.922383\n",
            "INFO:tensorflow:Saving 'checkpoint_path' summary for global step 1200: /tmp/tmp5k_alarh/model.ckpt-1200\n",
            "INFO:tensorflow:Calling model_fn.\n",
            "WARNING:tensorflow:Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x7f62934fb748>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Num'\n",
            "WARNING: Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x7f62934fb748>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Num'\n",
            "INFO:tensorflow:Done calling model_fn.\n",
            "INFO:tensorflow:Starting evaluation at 2021-02-08T20:32:53Z\n",
            "INFO:tensorflow:Graph was finalized.\n",
            "INFO:tensorflow:Restoring parameters from /tmp/tmpwqimbccp/model.ckpt-1200\n",
            "INFO:tensorflow:Running local_init_op.\n",
            "INFO:tensorflow:Done running local_init_op.\n",
            "INFO:tensorflow:Finished evaluation at 2021-02-08-20:32:53\n",
            "INFO:tensorflow:Saving dict for global step 1200: accuracy = 0.8095238, average_loss = 0.82816535, global_step = 1200, loss = 17.391472\n",
            "INFO:tensorflow:Saving 'checkpoint_path' summary for global step 1200: /tmp/tmpwqimbccp/model.ckpt-1200\n",
            "INFO:tensorflow:Calling model_fn.\n",
            "WARNING:tensorflow:Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x7f6290f1a470>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Num'\n",
            "WARNING: Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x7f6290f1a470>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Num'\n",
            "INFO:tensorflow:Done calling model_fn.\n",
            "INFO:tensorflow:Starting evaluation at 2021-02-08T20:32:54Z\n",
            "INFO:tensorflow:Graph was finalized.\n",
            "INFO:tensorflow:Restoring parameters from /tmp/tmpiwnz44j5/model.ckpt-1200\n",
            "INFO:tensorflow:Running local_init_op.\n",
            "INFO:tensorflow:Done running local_init_op.\n",
            "INFO:tensorflow:Finished evaluation at 2021-02-08-20:32:54\n",
            "INFO:tensorflow:Saving dict for global step 1200: accuracy = 0.8095238, average_loss = 0.6426422, global_step = 1200, loss = 13.495486\n",
            "INFO:tensorflow:Saving 'checkpoint_path' summary for global step 1200: /tmp/tmpiwnz44j5/model.ckpt-1200\n",
            "INFO:tensorflow:Calling model_fn.\n",
            "WARNING:tensorflow:Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x7f6292eef630>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Num'\n",
            "WARNING: Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x7f6292eef630>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Num'\n",
            "INFO:tensorflow:Done calling model_fn.\n",
            "INFO:tensorflow:Starting evaluation at 2021-02-08T20:32:55Z\n",
            "INFO:tensorflow:Graph was finalized.\n",
            "INFO:tensorflow:Restoring parameters from /tmp/tmpskkjmtj7/model.ckpt-1200\n",
            "INFO:tensorflow:Running local_init_op.\n",
            "INFO:tensorflow:Done running local_init_op.\n",
            "INFO:tensorflow:Finished evaluation at 2021-02-08-20:32:55\n",
            "INFO:tensorflow:Saving dict for global step 1200: accuracy = 0.8095238, average_loss = 0.63802266, global_step = 1200, loss = 13.398476\n",
            "INFO:tensorflow:Saving 'checkpoint_path' summary for global step 1200: /tmp/tmpskkjmtj7/model.ckpt-1200\n",
            "INFO:tensorflow:Calling model_fn.\n",
            "WARNING:tensorflow:Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x7f6290fe2be0>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Num'\n",
            "WARNING: Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x7f6290fe2be0>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Num'\n",
            "INFO:tensorflow:Done calling model_fn.\n",
            "INFO:tensorflow:Starting evaluation at 2021-02-08T20:32:56Z\n",
            "INFO:tensorflow:Graph was finalized.\n",
            "INFO:tensorflow:Restoring parameters from /tmp/tmpc5qcdo4t/model.ckpt-1200\n",
            "INFO:tensorflow:Running local_init_op.\n",
            "INFO:tensorflow:Done running local_init_op.\n",
            "INFO:tensorflow:Finished evaluation at 2021-02-08-20:32:56\n",
            "INFO:tensorflow:Saving dict for global step 1200: accuracy = 0.8095238, average_loss = 0.5732728, global_step = 1200, loss = 12.03873\n",
            "INFO:tensorflow:Saving 'checkpoint_path' summary for global step 1200: /tmp/tmpc5qcdo4t/model.ckpt-1200\n",
            "INFO:tensorflow:Calling model_fn.\n",
            "WARNING:tensorflow:Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x7f6293533a20>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Num'\n",
            "WARNING: Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x7f6293533a20>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Num'\n",
            "INFO:tensorflow:Done calling model_fn.\n",
            "INFO:tensorflow:Starting evaluation at 2021-02-08T20:32:56Z\n",
            "INFO:tensorflow:Graph was finalized.\n",
            "INFO:tensorflow:Restoring parameters from /tmp/tmpq201r8u9/model.ckpt-1200\n",
            "INFO:tensorflow:Running local_init_op.\n",
            "INFO:tensorflow:Done running local_init_op.\n",
            "INFO:tensorflow:Finished evaluation at 2021-02-08-20:32:57\n",
            "INFO:tensorflow:Saving dict for global step 1200: accuracy = 0.5714286, average_loss = 0.6827726, global_step = 1200, loss = 14.338224\n",
            "INFO:tensorflow:Saving 'checkpoint_path' summary for global step 1200: /tmp/tmpq201r8u9/model.ckpt-1200\n",
            "INFO:tensorflow:Calling model_fn.\n",
            "WARNING:tensorflow:Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x7f62986c11d0>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Num'\n",
            "WARNING: Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x7f62986c11d0>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Num'\n",
            "INFO:tensorflow:Done calling model_fn.\n",
            "INFO:tensorflow:Starting evaluation at 2021-02-08T20:32:57Z\n",
            "INFO:tensorflow:Graph was finalized.\n",
            "INFO:tensorflow:Restoring parameters from /tmp/tmphp5sqkg7/model.ckpt-1200\n",
            "INFO:tensorflow:Running local_init_op.\n",
            "INFO:tensorflow:Done running local_init_op.\n",
            "INFO:tensorflow:Finished evaluation at 2021-02-08-20:32:57\n",
            "INFO:tensorflow:Saving dict for global step 1200: accuracy = 0.8095238, average_loss = 0.61703557, global_step = 1200, loss = 12.9577465\n",
            "INFO:tensorflow:Saving 'checkpoint_path' summary for global step 1200: /tmp/tmphp5sqkg7/model.ckpt-1200\n",
            "INFO:tensorflow:Calling model_fn.\n",
            "WARNING:tensorflow:Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x7f629364ce48>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Num'\n",
            "WARNING: Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x7f629364ce48>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Num'\n",
            "INFO:tensorflow:Done calling model_fn.\n",
            "INFO:tensorflow:Starting evaluation at 2021-02-08T20:32:58Z\n",
            "INFO:tensorflow:Graph was finalized.\n",
            "INFO:tensorflow:Restoring parameters from /tmp/tmpc785szw4/model.ckpt-1200\n",
            "INFO:tensorflow:Running local_init_op.\n",
            "INFO:tensorflow:Done running local_init_op.\n",
            "INFO:tensorflow:Finished evaluation at 2021-02-08-20:32:58\n",
            "INFO:tensorflow:Saving dict for global step 1200: accuracy = 0.8095238, average_loss = 0.5610531, global_step = 1200, loss = 11.782115\n",
            "INFO:tensorflow:Saving 'checkpoint_path' summary for global step 1200: /tmp/tmpc785szw4/model.ckpt-1200\n",
            "INFO:tensorflow:Calling model_fn.\n",
            "WARNING:tensorflow:Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x7f6293296d68>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Num'\n",
            "WARNING: Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x7f6293296d68>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Num'\n",
            "INFO:tensorflow:Done calling model_fn.\n",
            "INFO:tensorflow:Starting evaluation at 2021-02-08T20:32:59Z\n",
            "INFO:tensorflow:Graph was finalized.\n",
            "INFO:tensorflow:Restoring parameters from /tmp/tmptvdwjojq/model.ckpt-1200\n",
            "INFO:tensorflow:Running local_init_op.\n",
            "INFO:tensorflow:Done running local_init_op.\n",
            "INFO:tensorflow:Finished evaluation at 2021-02-08-20:32:59\n",
            "INFO:tensorflow:Saving dict for global step 1200: accuracy = 0.8095238, average_loss = 0.69733036, global_step = 1200, loss = 14.643938\n",
            "INFO:tensorflow:Saving 'checkpoint_path' summary for global step 1200: /tmp/tmptvdwjojq/model.ckpt-1200\n",
            "INFO:tensorflow:Calling model_fn.\n",
            "WARNING:tensorflow:Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x7f6290eb8d30>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Num'\n",
            "WARNING: Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x7f6290eb8d30>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Num'\n",
            "INFO:tensorflow:Done calling model_fn.\n",
            "INFO:tensorflow:Starting evaluation at 2021-02-08T20:32:59Z\n",
            "INFO:tensorflow:Graph was finalized.\n",
            "INFO:tensorflow:Restoring parameters from /tmp/tmpq9g05251/model.ckpt-1200\n",
            "INFO:tensorflow:Running local_init_op.\n",
            "INFO:tensorflow:Done running local_init_op.\n",
            "INFO:tensorflow:Finished evaluation at 2021-02-08-20:33:00\n",
            "INFO:tensorflow:Saving dict for global step 1200: accuracy = 0.8095238, average_loss = 0.82991666, global_step = 1200, loss = 17.42825\n",
            "INFO:tensorflow:Saving 'checkpoint_path' summary for global step 1200: /tmp/tmpq9g05251/model.ckpt-1200\n",
            "INFO:tensorflow:Calling model_fn.\n",
            "WARNING:tensorflow:Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x7f6292d003c8>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Num'\n",
            "WARNING: Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x7f6292d003c8>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Num'\n",
            "INFO:tensorflow:Done calling model_fn.\n",
            "INFO:tensorflow:Starting evaluation at 2021-02-08T20:33:00Z\n",
            "INFO:tensorflow:Graph was finalized.\n",
            "INFO:tensorflow:Restoring parameters from /tmp/tmpci9mwzk2/model.ckpt-1200\n",
            "INFO:tensorflow:Running local_init_op.\n",
            "INFO:tensorflow:Done running local_init_op.\n",
            "INFO:tensorflow:Finished evaluation at 2021-02-08-20:33:01\n",
            "INFO:tensorflow:Saving dict for global step 1200: accuracy = 0.85714287, average_loss = 0.4871138, global_step = 1200, loss = 10.22939\n",
            "INFO:tensorflow:Saving 'checkpoint_path' summary for global step 1200: /tmp/tmpci9mwzk2/model.ckpt-1200\n",
            "INFO:tensorflow:Calling model_fn.\n",
            "WARNING:tensorflow:Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x7f629106f6a0>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Num'\n",
            "WARNING: Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x7f629106f6a0>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Num'\n",
            "INFO:tensorflow:Done calling model_fn.\n",
            "INFO:tensorflow:Starting evaluation at 2021-02-08T20:33:01Z\n",
            "INFO:tensorflow:Graph was finalized.\n",
            "INFO:tensorflow:Restoring parameters from /tmp/tmppmx_icyg/model.ckpt-1200\n",
            "INFO:tensorflow:Running local_init_op.\n",
            "INFO:tensorflow:Done running local_init_op.\n",
            "INFO:tensorflow:Finished evaluation at 2021-02-08-20:33:02\n",
            "INFO:tensorflow:Saving dict for global step 1200: accuracy = 0.9047619, average_loss = 0.40909657, global_step = 1200, loss = 8.591028\n",
            "INFO:tensorflow:Saving 'checkpoint_path' summary for global step 1200: /tmp/tmppmx_icyg/model.ckpt-1200\n",
            "INFO:tensorflow:Calling model_fn.\n",
            "WARNING:tensorflow:Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x7f6292d24668>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Num'\n",
            "WARNING: Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x7f6292d24668>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Num'\n",
            "INFO:tensorflow:Done calling model_fn.\n",
            "INFO:tensorflow:Starting evaluation at 2021-02-08T20:33:02Z\n",
            "INFO:tensorflow:Graph was finalized.\n",
            "INFO:tensorflow:Restoring parameters from /tmp/tmpml51mpk4/model.ckpt-1200\n",
            "INFO:tensorflow:Running local_init_op.\n",
            "INFO:tensorflow:Done running local_init_op.\n",
            "INFO:tensorflow:Finished evaluation at 2021-02-08-20:33:02\n",
            "INFO:tensorflow:Saving dict for global step 1200: accuracy = 0.8095238, average_loss = 0.4779547, global_step = 1200, loss = 10.037048\n",
            "INFO:tensorflow:Saving 'checkpoint_path' summary for global step 1200: /tmp/tmpml51mpk4/model.ckpt-1200\n",
            "INFO:tensorflow:Calling model_fn.\n",
            "WARNING:tensorflow:Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x7f6292eb55c0>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Num'\n",
            "WARNING: Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x7f6292eb55c0>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Num'\n",
            "INFO:tensorflow:Done calling model_fn.\n",
            "INFO:tensorflow:Starting evaluation at 2021-02-08T20:33:03Z\n",
            "INFO:tensorflow:Graph was finalized.\n",
            "INFO:tensorflow:Restoring parameters from /tmp/tmp2tw3bc1t/model.ckpt-1200\n",
            "INFO:tensorflow:Running local_init_op.\n",
            "INFO:tensorflow:Done running local_init_op.\n",
            "INFO:tensorflow:Finished evaluation at 2021-02-08-20:33:03\n",
            "INFO:tensorflow:Saving dict for global step 1200: accuracy = 0.8095238, average_loss = 0.4307776, global_step = 1200, loss = 9.0463295\n",
            "INFO:tensorflow:Saving 'checkpoint_path' summary for global step 1200: /tmp/tmp2tw3bc1t/model.ckpt-1200\n",
            "INFO:tensorflow:Calling model_fn.\n",
            "WARNING:tensorflow:Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x7f6290e00e80>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Num'\n",
            "WARNING: Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x7f6290e00e80>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Num'\n",
            "INFO:tensorflow:Done calling model_fn.\n",
            "INFO:tensorflow:Starting evaluation at 2021-02-08T20:33:04Z\n",
            "INFO:tensorflow:Graph was finalized.\n",
            "INFO:tensorflow:Restoring parameters from /tmp/tmpwbvwdjbj/model.ckpt-1200\n",
            "INFO:tensorflow:Running local_init_op.\n",
            "INFO:tensorflow:Done running local_init_op.\n",
            "INFO:tensorflow:Finished evaluation at 2021-02-08-20:33:04\n",
            "INFO:tensorflow:Saving dict for global step 1200: accuracy = 0.85714287, average_loss = 0.41937023, global_step = 1200, loss = 8.806775\n",
            "INFO:tensorflow:Saving 'checkpoint_path' summary for global step 1200: /tmp/tmpwbvwdjbj/model.ckpt-1200\n",
            "INFO:tensorflow:Calling model_fn.\n",
            "WARNING:tensorflow:Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x7f6293387c50>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Num'\n",
            "WARNING: Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x7f6293387c50>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Num'\n",
            "INFO:tensorflow:Done calling model_fn.\n",
            "INFO:tensorflow:Starting evaluation at 2021-02-08T20:33:04Z\n",
            "INFO:tensorflow:Graph was finalized.\n",
            "INFO:tensorflow:Restoring parameters from /tmp/tmput85gder/model.ckpt-1200\n",
            "INFO:tensorflow:Running local_init_op.\n",
            "INFO:tensorflow:Done running local_init_op.\n",
            "INFO:tensorflow:Finished evaluation at 2021-02-08-20:33:05\n",
            "INFO:tensorflow:Saving dict for global step 1200: accuracy = 0.8095238, average_loss = 0.6453433, global_step = 1200, loss = 13.552209\n",
            "INFO:tensorflow:Saving 'checkpoint_path' summary for global step 1200: /tmp/tmput85gder/model.ckpt-1200\n",
            "INFO:tensorflow:Calling model_fn.\n",
            "WARNING:tensorflow:Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x7f6292f57710>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Num'\n",
            "WARNING: Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x7f6292f57710>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Num'\n",
            "INFO:tensorflow:Done calling model_fn.\n",
            "INFO:tensorflow:Starting evaluation at 2021-02-08T20:33:05Z\n",
            "INFO:tensorflow:Graph was finalized.\n",
            "INFO:tensorflow:Restoring parameters from /tmp/tmpsi2wdkq_/model.ckpt-1200\n",
            "INFO:tensorflow:Running local_init_op.\n",
            "INFO:tensorflow:Done running local_init_op.\n",
            "INFO:tensorflow:Finished evaluation at 2021-02-08-20:33:06\n",
            "INFO:tensorflow:Saving dict for global step 1200: accuracy = 0.85714287, average_loss = 0.53653616, global_step = 1200, loss = 11.26726\n",
            "INFO:tensorflow:Saving 'checkpoint_path' summary for global step 1200: /tmp/tmpsi2wdkq_/model.ckpt-1200\n",
            "INFO:tensorflow:Calling model_fn.\n",
            "WARNING:tensorflow:Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x7f6293693a90>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Num'\n",
            "WARNING: Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x7f6293693a90>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Num'\n",
            "INFO:tensorflow:Done calling model_fn.\n",
            "INFO:tensorflow:Starting evaluation at 2021-02-08T20:33:06Z\n",
            "INFO:tensorflow:Graph was finalized.\n",
            "INFO:tensorflow:Restoring parameters from /tmp/tmpvck54j30/model.ckpt-1200\n",
            "INFO:tensorflow:Running local_init_op.\n",
            "INFO:tensorflow:Done running local_init_op.\n",
            "INFO:tensorflow:Finished evaluation at 2021-02-08-20:33:06\n",
            "INFO:tensorflow:Saving dict for global step 1200: accuracy = 0.61904764, average_loss = 0.7349393, global_step = 1200, loss = 15.433725\n",
            "INFO:tensorflow:Saving 'checkpoint_path' summary for global step 1200: /tmp/tmpvck54j30/model.ckpt-1200\n",
            "INFO:tensorflow:Calling model_fn.\n",
            "WARNING:tensorflow:Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x7f6290ddcbe0>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Num'\n",
            "WARNING: Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x7f6290ddcbe0>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Num'\n",
            "INFO:tensorflow:Done calling model_fn.\n",
            "INFO:tensorflow:Starting evaluation at 2021-02-08T20:33:07Z\n",
            "INFO:tensorflow:Graph was finalized.\n",
            "INFO:tensorflow:Restoring parameters from /tmp/tmp590z9urv/model.ckpt-1200\n",
            "INFO:tensorflow:Running local_init_op.\n",
            "INFO:tensorflow:Done running local_init_op.\n",
            "INFO:tensorflow:Finished evaluation at 2021-02-08-20:33:07\n",
            "INFO:tensorflow:Saving dict for global step 1200: accuracy = 0.8095238, average_loss = 0.6508624, global_step = 1200, loss = 13.66811\n",
            "INFO:tensorflow:Saving 'checkpoint_path' summary for global step 1200: /tmp/tmp590z9urv/model.ckpt-1200\n",
            "INFO:tensorflow:Calling model_fn.\n",
            "WARNING:tensorflow:Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x7f6292c3e860>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Num'\n",
            "WARNING: Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x7f6292c3e860>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Num'\n",
            "INFO:tensorflow:Done calling model_fn.\n",
            "INFO:tensorflow:Starting evaluation at 2021-02-08T20:33:08Z\n",
            "INFO:tensorflow:Graph was finalized.\n",
            "INFO:tensorflow:Restoring parameters from /tmp/tmptjvp7ttc/model.ckpt-1200\n",
            "INFO:tensorflow:Running local_init_op.\n",
            "INFO:tensorflow:Done running local_init_op.\n",
            "INFO:tensorflow:Finished evaluation at 2021-02-08-20:33:08\n",
            "INFO:tensorflow:Saving dict for global step 1200: accuracy = 0.85714287, average_loss = 0.540572, global_step = 1200, loss = 11.352012\n",
            "INFO:tensorflow:Saving 'checkpoint_path' summary for global step 1200: /tmp/tmptjvp7ttc/model.ckpt-1200\n",
            "INFO:tensorflow:Calling model_fn.\n",
            "WARNING:tensorflow:Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x7f6292c1bb38>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Num'\n",
            "WARNING: Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x7f6292c1bb38>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Num'\n",
            "INFO:tensorflow:Done calling model_fn.\n",
            "INFO:tensorflow:Starting evaluation at 2021-02-08T20:33:08Z\n",
            "INFO:tensorflow:Graph was finalized.\n",
            "INFO:tensorflow:Restoring parameters from /tmp/tmpab_leqvh/model.ckpt-1200\n",
            "INFO:tensorflow:Running local_init_op.\n",
            "INFO:tensorflow:Done running local_init_op.\n",
            "INFO:tensorflow:Finished evaluation at 2021-02-08-20:33:09\n",
            "INFO:tensorflow:Saving dict for global step 1200: accuracy = 0.8095238, average_loss = 0.57854724, global_step = 1200, loss = 12.149492\n",
            "INFO:tensorflow:Saving 'checkpoint_path' summary for global step 1200: /tmp/tmpab_leqvh/model.ckpt-1200\n",
            "INFO:tensorflow:Calling model_fn.\n",
            "WARNING:tensorflow:Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x7f6290eee080>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Num'\n",
            "WARNING: Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x7f6290eee080>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Num'\n",
            "INFO:tensorflow:Done calling model_fn.\n",
            "INFO:tensorflow:Starting evaluation at 2021-02-08T20:33:09Z\n",
            "INFO:tensorflow:Graph was finalized.\n",
            "INFO:tensorflow:Restoring parameters from /tmp/tmp6zcx_uh3/model.ckpt-1200\n",
            "INFO:tensorflow:Running local_init_op.\n",
            "INFO:tensorflow:Done running local_init_op.\n",
            "INFO:tensorflow:Finished evaluation at 2021-02-08-20:33:10\n",
            "INFO:tensorflow:Saving dict for global step 1200: accuracy = 0.85714287, average_loss = 0.2558333, global_step = 1200, loss = 5.372499\n",
            "INFO:tensorflow:Saving 'checkpoint_path' summary for global step 1200: /tmp/tmp6zcx_uh3/model.ckpt-1200\n",
            "INFO:tensorflow:Calling model_fn.\n",
            "WARNING:tensorflow:Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x7f6292ccb400>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Num'\n",
            "WARNING: Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x7f6292ccb400>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Num'\n",
            "INFO:tensorflow:Done calling model_fn.\n",
            "INFO:tensorflow:Starting evaluation at 2021-02-08T20:33:10Z\n",
            "INFO:tensorflow:Graph was finalized.\n",
            "INFO:tensorflow:Restoring parameters from /tmp/tmp2f9ghpad/model.ckpt-1200\n",
            "INFO:tensorflow:Running local_init_op.\n",
            "INFO:tensorflow:Done running local_init_op.\n",
            "INFO:tensorflow:Finished evaluation at 2021-02-08-20:33:11\n",
            "INFO:tensorflow:Saving dict for global step 1200: accuracy = 0.8095238, average_loss = 0.6611249, global_step = 1200, loss = 13.883622\n",
            "INFO:tensorflow:Saving 'checkpoint_path' summary for global step 1200: /tmp/tmp2f9ghpad/model.ckpt-1200\n",
            "INFO:tensorflow:Calling model_fn.\n",
            "WARNING:tensorflow:Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x7f629133d550>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Num'\n",
            "WARNING: Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x7f629133d550>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Num'\n",
            "INFO:tensorflow:Done calling model_fn.\n",
            "INFO:tensorflow:Starting evaluation at 2021-02-08T20:33:11Z\n",
            "INFO:tensorflow:Graph was finalized.\n",
            "INFO:tensorflow:Restoring parameters from /tmp/tmpff26fjnc/model.ckpt-1200\n",
            "INFO:tensorflow:Running local_init_op.\n",
            "INFO:tensorflow:Done running local_init_op.\n",
            "INFO:tensorflow:Finished evaluation at 2021-02-08-20:33:11\n",
            "INFO:tensorflow:Saving dict for global step 1200: accuracy = 0.9047619, average_loss = 0.53793555, global_step = 1200, loss = 11.296646\n",
            "INFO:tensorflow:Saving 'checkpoint_path' summary for global step 1200: /tmp/tmpff26fjnc/model.ckpt-1200\n",
            "INFO:tensorflow:Calling model_fn.\n",
            "WARNING:tensorflow:Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x7f62933ef748>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Num'\n",
            "WARNING: Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x7f62933ef748>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Num'\n",
            "INFO:tensorflow:Done calling model_fn.\n",
            "INFO:tensorflow:Starting evaluation at 2021-02-08T20:33:12Z\n",
            "INFO:tensorflow:Graph was finalized.\n",
            "INFO:tensorflow:Restoring parameters from /tmp/tmpn34496y8/model.ckpt-1200\n",
            "INFO:tensorflow:Running local_init_op.\n",
            "INFO:tensorflow:Done running local_init_op.\n",
            "INFO:tensorflow:Finished evaluation at 2021-02-08-20:33:12\n",
            "INFO:tensorflow:Saving dict for global step 1200: accuracy = 0.85714287, average_loss = 0.56787694, global_step = 1200, loss = 11.925416\n",
            "INFO:tensorflow:Saving 'checkpoint_path' summary for global step 1200: /tmp/tmpn34496y8/model.ckpt-1200\n",
            "INFO:tensorflow:Calling model_fn.\n",
            "WARNING:tensorflow:Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x7f62985bb550>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Num'\n",
            "WARNING: Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x7f62985bb550>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Num'\n",
            "INFO:tensorflow:Done calling model_fn.\n",
            "INFO:tensorflow:Starting evaluation at 2021-02-08T20:33:13Z\n",
            "INFO:tensorflow:Graph was finalized.\n",
            "INFO:tensorflow:Restoring parameters from /tmp/tmpkyl_rt6w/model.ckpt-1200\n",
            "INFO:tensorflow:Running local_init_op.\n",
            "INFO:tensorflow:Done running local_init_op.\n",
            "INFO:tensorflow:Finished evaluation at 2021-02-08-20:33:13\n",
            "INFO:tensorflow:Saving dict for global step 1200: accuracy = 0.8095238, average_loss = 0.45979792, global_step = 1200, loss = 9.655756\n",
            "INFO:tensorflow:Saving 'checkpoint_path' summary for global step 1200: /tmp/tmpkyl_rt6w/model.ckpt-1200\n",
            "INFO:tensorflow:Calling model_fn.\n",
            "WARNING:tensorflow:Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x7f6292ceccc0>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Num'\n",
            "WARNING: Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x7f6292ceccc0>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Num'\n",
            "INFO:tensorflow:Done calling model_fn.\n",
            "INFO:tensorflow:Starting evaluation at 2021-02-08T20:33:13Z\n",
            "INFO:tensorflow:Graph was finalized.\n",
            "INFO:tensorflow:Restoring parameters from /tmp/tmp3wobm_43/model.ckpt-1200\n",
            "INFO:tensorflow:Running local_init_op.\n",
            "INFO:tensorflow:Done running local_init_op.\n",
            "INFO:tensorflow:Finished evaluation at 2021-02-08-20:33:14\n",
            "INFO:tensorflow:Saving dict for global step 1200: accuracy = 0.85714287, average_loss = 0.47884628, global_step = 1200, loss = 10.055772\n",
            "INFO:tensorflow:Saving 'checkpoint_path' summary for global step 1200: /tmp/tmp3wobm_43/model.ckpt-1200\n",
            "INFO:tensorflow:Calling model_fn.\n",
            "WARNING:tensorflow:Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x7f6292d96a90>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Num'\n",
            "WARNING: Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x7f6292d96a90>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Num'\n",
            "INFO:tensorflow:Done calling model_fn.\n",
            "INFO:tensorflow:Starting evaluation at 2021-02-08T20:33:14Z\n",
            "INFO:tensorflow:Graph was finalized.\n",
            "INFO:tensorflow:Restoring parameters from /tmp/tmpdya1mth4/model.ckpt-1200\n",
            "INFO:tensorflow:Running local_init_op.\n",
            "INFO:tensorflow:Done running local_init_op.\n",
            "INFO:tensorflow:Finished evaluation at 2021-02-08-20:33:15\n",
            "INFO:tensorflow:Saving dict for global step 1200: accuracy = 0.85714287, average_loss = 0.651678, global_step = 1200, loss = 13.685239\n",
            "INFO:tensorflow:Saving 'checkpoint_path' summary for global step 1200: /tmp/tmpdya1mth4/model.ckpt-1200\n",
            "INFO:tensorflow:Calling model_fn.\n",
            "WARNING:tensorflow:Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x7f62931d0eb8>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Num'\n",
            "WARNING: Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x7f62931d0eb8>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Num'\n",
            "INFO:tensorflow:Done calling model_fn.\n",
            "INFO:tensorflow:Starting evaluation at 2021-02-08T20:33:15Z\n",
            "INFO:tensorflow:Graph was finalized.\n",
            "INFO:tensorflow:Restoring parameters from /tmp/tmp9x1h7xux/model.ckpt-1200\n",
            "INFO:tensorflow:Running local_init_op.\n",
            "INFO:tensorflow:Done running local_init_op.\n",
            "INFO:tensorflow:Finished evaluation at 2021-02-08-20:33:15\n",
            "INFO:tensorflow:Saving dict for global step 1200: accuracy = 0.8095238, average_loss = 0.65759766, global_step = 1200, loss = 13.809551\n",
            "INFO:tensorflow:Saving 'checkpoint_path' summary for global step 1200: /tmp/tmp9x1h7xux/model.ckpt-1200\n",
            "INFO:tensorflow:Calling model_fn.\n",
            "WARNING:tensorflow:Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x7f6290da70f0>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Num'\n",
            "WARNING: Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x7f6290da70f0>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Num'\n",
            "INFO:tensorflow:Done calling model_fn.\n",
            "INFO:tensorflow:Starting evaluation at 2021-02-08T20:33:16Z\n",
            "INFO:tensorflow:Graph was finalized.\n",
            "INFO:tensorflow:Restoring parameters from /tmp/tmp5zej0iaq/model.ckpt-1200\n",
            "INFO:tensorflow:Running local_init_op.\n",
            "INFO:tensorflow:Done running local_init_op.\n",
            "INFO:tensorflow:Finished evaluation at 2021-02-08-20:33:16\n",
            "INFO:tensorflow:Saving dict for global step 1200: accuracy = 0.8095238, average_loss = 1.0014406, global_step = 1200, loss = 21.030252\n",
            "INFO:tensorflow:Saving 'checkpoint_path' summary for global step 1200: /tmp/tmp5zej0iaq/model.ckpt-1200\n",
            "INFO:tensorflow:Calling model_fn.\n",
            "WARNING:tensorflow:Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x7f6290f882e8>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Num'\n",
            "WARNING: Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x7f6290f882e8>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Num'\n",
            "INFO:tensorflow:Done calling model_fn.\n",
            "INFO:tensorflow:Starting evaluation at 2021-02-08T20:33:17Z\n",
            "INFO:tensorflow:Graph was finalized.\n",
            "INFO:tensorflow:Restoring parameters from /tmp/tmpsv714lwx/model.ckpt-1200\n",
            "INFO:tensorflow:Running local_init_op.\n",
            "INFO:tensorflow:Done running local_init_op.\n",
            "INFO:tensorflow:Finished evaluation at 2021-02-08-20:33:17\n",
            "INFO:tensorflow:Saving dict for global step 1200: accuracy = 0.8095238, average_loss = 0.66855395, global_step = 1200, loss = 14.039633\n",
            "INFO:tensorflow:Saving 'checkpoint_path' summary for global step 1200: /tmp/tmpsv714lwx/model.ckpt-1200\n",
            "INFO:tensorflow:Calling model_fn.\n",
            "WARNING:tensorflow:Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x7f6290c98160>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Num'\n",
            "WARNING: Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x7f6290c98160>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Num'\n",
            "INFO:tensorflow:Done calling model_fn.\n",
            "INFO:tensorflow:Starting evaluation at 2021-02-08T20:33:18Z\n",
            "INFO:tensorflow:Graph was finalized.\n",
            "INFO:tensorflow:Restoring parameters from /tmp/tmpvg0ciubu/model.ckpt-1200\n",
            "INFO:tensorflow:Running local_init_op.\n",
            "INFO:tensorflow:Done running local_init_op.\n",
            "INFO:tensorflow:Finished evaluation at 2021-02-08-20:33:18\n",
            "INFO:tensorflow:Saving dict for global step 1200: accuracy = 0.8095238, average_loss = 0.6131333, global_step = 1200, loss = 12.875799\n",
            "INFO:tensorflow:Saving 'checkpoint_path' summary for global step 1200: /tmp/tmpvg0ciubu/model.ckpt-1200\n",
            "INFO:tensorflow:Calling model_fn.\n",
            "WARNING:tensorflow:Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x7f6291145588>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Num'\n",
            "WARNING: Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x7f6291145588>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Num'\n",
            "INFO:tensorflow:Done calling model_fn.\n",
            "INFO:tensorflow:Starting evaluation at 2021-02-08T20:33:18Z\n",
            "INFO:tensorflow:Graph was finalized.\n",
            "INFO:tensorflow:Restoring parameters from /tmp/tmpmy6txchs/model.ckpt-1200\n",
            "INFO:tensorflow:Running local_init_op.\n",
            "INFO:tensorflow:Done running local_init_op.\n",
            "INFO:tensorflow:Finished evaluation at 2021-02-08-20:33:19\n",
            "INFO:tensorflow:Saving dict for global step 1200: accuracy = 0.61904764, average_loss = 0.688868, global_step = 1200, loss = 14.466228\n",
            "INFO:tensorflow:Saving 'checkpoint_path' summary for global step 1200: /tmp/tmpmy6txchs/model.ckpt-1200\n",
            "INFO:tensorflow:Calling model_fn.\n",
            "WARNING:tensorflow:Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x7f62932ef5f8>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Num'\n",
            "WARNING: Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x7f62932ef5f8>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Num'\n",
            "INFO:tensorflow:Done calling model_fn.\n",
            "INFO:tensorflow:Starting evaluation at 2021-02-08T20:33:19Z\n",
            "INFO:tensorflow:Graph was finalized.\n",
            "INFO:tensorflow:Restoring parameters from /tmp/tmpmpiaw7jh/model.ckpt-1200\n",
            "INFO:tensorflow:Running local_init_op.\n",
            "INFO:tensorflow:Done running local_init_op.\n",
            "INFO:tensorflow:Finished evaluation at 2021-02-08-20:33:20\n",
            "INFO:tensorflow:Saving dict for global step 1200: accuracy = 0.8095238, average_loss = 0.6159293, global_step = 1200, loss = 12.934515\n",
            "INFO:tensorflow:Saving 'checkpoint_path' summary for global step 1200: /tmp/tmpmpiaw7jh/model.ckpt-1200\n",
            "INFO:tensorflow:Calling model_fn.\n",
            "WARNING:tensorflow:Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x7f62911a4400>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Num'\n",
            "WARNING: Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x7f62911a4400>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Num'\n",
            "INFO:tensorflow:Done calling model_fn.\n",
            "INFO:tensorflow:Starting evaluation at 2021-02-08T20:33:20Z\n",
            "INFO:tensorflow:Graph was finalized.\n",
            "INFO:tensorflow:Restoring parameters from /tmp/tmpp99x_ex0/model.ckpt-1200\n",
            "INFO:tensorflow:Running local_init_op.\n",
            "INFO:tensorflow:Done running local_init_op.\n",
            "INFO:tensorflow:Finished evaluation at 2021-02-08-20:33:20\n",
            "INFO:tensorflow:Saving dict for global step 1200: accuracy = 0.8095238, average_loss = 0.46281934, global_step = 1200, loss = 9.719206\n",
            "INFO:tensorflow:Saving 'checkpoint_path' summary for global step 1200: /tmp/tmpp99x_ex0/model.ckpt-1200\n",
            "INFO:tensorflow:Calling model_fn.\n",
            "WARNING:tensorflow:Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x7f6292f520f0>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Num'\n",
            "WARNING: Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x7f6292f520f0>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Num'\n",
            "INFO:tensorflow:Done calling model_fn.\n",
            "INFO:tensorflow:Starting evaluation at 2021-02-08T20:33:21Z\n",
            "INFO:tensorflow:Graph was finalized.\n",
            "INFO:tensorflow:Restoring parameters from /tmp/tmp535bpj5q/model.ckpt-1200\n",
            "INFO:tensorflow:Running local_init_op.\n",
            "INFO:tensorflow:Done running local_init_op.\n",
            "INFO:tensorflow:Finished evaluation at 2021-02-08-20:33:21\n",
            "INFO:tensorflow:Saving dict for global step 1200: accuracy = 0.7619048, average_loss = 0.5274072, global_step = 1200, loss = 11.075552\n",
            "INFO:tensorflow:Saving 'checkpoint_path' summary for global step 1200: /tmp/tmp535bpj5q/model.ckpt-1200\n",
            "INFO:tensorflow:Calling model_fn.\n",
            "WARNING:tensorflow:Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x7f6291009c18>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Num'\n",
            "WARNING: Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x7f6291009c18>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Num'\n",
            "INFO:tensorflow:Done calling model_fn.\n",
            "INFO:tensorflow:Starting evaluation at 2021-02-08T20:33:22Z\n",
            "INFO:tensorflow:Graph was finalized.\n",
            "INFO:tensorflow:Restoring parameters from /tmp/tmpnut55lpv/model.ckpt-1200\n",
            "INFO:tensorflow:Running local_init_op.\n",
            "INFO:tensorflow:Done running local_init_op.\n",
            "INFO:tensorflow:Finished evaluation at 2021-02-08-20:33:22\n",
            "INFO:tensorflow:Saving dict for global step 1200: accuracy = 0.8095238, average_loss = 0.615347, global_step = 1200, loss = 12.922287\n",
            "INFO:tensorflow:Saving 'checkpoint_path' summary for global step 1200: /tmp/tmpnut55lpv/model.ckpt-1200\n",
            "INFO:tensorflow:Calling model_fn.\n",
            "WARNING:tensorflow:Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x7f6290dad0f0>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Num'\n",
            "WARNING: Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x7f6290dad0f0>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Num'\n",
            "INFO:tensorflow:Done calling model_fn.\n",
            "INFO:tensorflow:Starting evaluation at 2021-02-08T20:33:22Z\n",
            "INFO:tensorflow:Graph was finalized.\n",
            "INFO:tensorflow:Restoring parameters from /tmp/tmpn1ec9csh/model.ckpt-1200\n",
            "INFO:tensorflow:Running local_init_op.\n",
            "INFO:tensorflow:Done running local_init_op.\n",
            "INFO:tensorflow:Finished evaluation at 2021-02-08-20:33:23\n",
            "INFO:tensorflow:Saving dict for global step 1200: accuracy = 0.8095238, average_loss = 0.55872655, global_step = 1200, loss = 11.733257\n",
            "INFO:tensorflow:Saving 'checkpoint_path' summary for global step 1200: /tmp/tmpn1ec9csh/model.ckpt-1200\n",
            "INFO:tensorflow:Calling model_fn.\n",
            "WARNING:tensorflow:Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x7f6293337908>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Num'\n",
            "WARNING: Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x7f6293337908>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Num'\n",
            "INFO:tensorflow:Done calling model_fn.\n",
            "INFO:tensorflow:Starting evaluation at 2021-02-08T20:33:23Z\n",
            "INFO:tensorflow:Graph was finalized.\n",
            "INFO:tensorflow:Restoring parameters from /tmp/tmpd46d3kq3/model.ckpt-1200\n",
            "INFO:tensorflow:Running local_init_op.\n",
            "INFO:tensorflow:Done running local_init_op.\n",
            "INFO:tensorflow:Finished evaluation at 2021-02-08-20:33:23\n",
            "INFO:tensorflow:Saving dict for global step 1200: accuracy = 0.7619048, average_loss = 1.2431778, global_step = 1200, loss = 26.106733\n",
            "INFO:tensorflow:Saving 'checkpoint_path' summary for global step 1200: /tmp/tmpd46d3kq3/model.ckpt-1200\n",
            "INFO:tensorflow:Calling model_fn.\n",
            "WARNING:tensorflow:Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x7f629136f550>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Num'\n",
            "WARNING: Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x7f629136f550>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Num'\n",
            "INFO:tensorflow:Done calling model_fn.\n",
            "INFO:tensorflow:Starting evaluation at 2021-02-08T20:33:24Z\n",
            "INFO:tensorflow:Graph was finalized.\n",
            "INFO:tensorflow:Restoring parameters from /tmp/tmph8ng643z/model.ckpt-1200\n",
            "INFO:tensorflow:Running local_init_op.\n",
            "INFO:tensorflow:Done running local_init_op.\n",
            "INFO:tensorflow:Finished evaluation at 2021-02-08-20:33:24\n",
            "INFO:tensorflow:Saving dict for global step 1200: accuracy = 0.8095238, average_loss = 0.6248586, global_step = 1200, loss = 13.122031\n",
            "INFO:tensorflow:Saving 'checkpoint_path' summary for global step 1200: /tmp/tmph8ng643z/model.ckpt-1200\n",
            "INFO:tensorflow:Calling model_fn.\n",
            "WARNING:tensorflow:Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x7f62931cc0b8>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Num'\n",
            "WARNING: Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x7f62931cc0b8>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Num'\n",
            "INFO:tensorflow:Done calling model_fn.\n",
            "INFO:tensorflow:Starting evaluation at 2021-02-08T20:33:25Z\n",
            "INFO:tensorflow:Graph was finalized.\n",
            "INFO:tensorflow:Restoring parameters from /tmp/tmpd6gib3ok/model.ckpt-1200\n",
            "INFO:tensorflow:Running local_init_op.\n",
            "INFO:tensorflow:Done running local_init_op.\n",
            "INFO:tensorflow:Finished evaluation at 2021-02-08-20:33:25\n",
            "INFO:tensorflow:Saving dict for global step 1200: accuracy = 0.8095238, average_loss = 0.7002802, global_step = 1200, loss = 14.705884\n",
            "INFO:tensorflow:Saving 'checkpoint_path' summary for global step 1200: /tmp/tmpd6gib3ok/model.ckpt-1200\n",
            "INFO:tensorflow:Calling model_fn.\n",
            "WARNING:tensorflow:Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x7f6290db9b70>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Num'\n",
            "WARNING: Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x7f6290db9b70>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Num'\n",
            "INFO:tensorflow:Done calling model_fn.\n",
            "INFO:tensorflow:Starting evaluation at 2021-02-08T20:33:26Z\n",
            "INFO:tensorflow:Graph was finalized.\n",
            "INFO:tensorflow:Restoring parameters from /tmp/tmpn25rxo0h/model.ckpt-1200\n",
            "INFO:tensorflow:Running local_init_op.\n",
            "INFO:tensorflow:Done running local_init_op.\n",
            "INFO:tensorflow:Finished evaluation at 2021-02-08-20:33:26\n",
            "INFO:tensorflow:Saving dict for global step 1200: accuracy = 0.85714287, average_loss = 0.39878818, global_step = 1200, loss = 8.374552\n",
            "INFO:tensorflow:Saving 'checkpoint_path' summary for global step 1200: /tmp/tmpn25rxo0h/model.ckpt-1200\n",
            "INFO:tensorflow:Calling model_fn.\n",
            "WARNING:tensorflow:Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x7f6292bf97b8>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Num'\n",
            "WARNING: Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x7f6292bf97b8>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Num'\n",
            "INFO:tensorflow:Done calling model_fn.\n",
            "INFO:tensorflow:Starting evaluation at 2021-02-08T20:33:27Z\n",
            "INFO:tensorflow:Graph was finalized.\n",
            "INFO:tensorflow:Restoring parameters from /tmp/tmp28j6cq3t/model.ckpt-1200\n",
            "INFO:tensorflow:Running local_init_op.\n",
            "INFO:tensorflow:Done running local_init_op.\n",
            "INFO:tensorflow:Finished evaluation at 2021-02-08-20:33:27\n",
            "INFO:tensorflow:Saving dict for global step 1200: accuracy = 0.8095238, average_loss = 0.6568141, global_step = 1200, loss = 13.793096\n",
            "INFO:tensorflow:Saving 'checkpoint_path' summary for global step 1200: /tmp/tmp28j6cq3t/model.ckpt-1200\n",
            "INFO:tensorflow:Calling model_fn.\n",
            "WARNING:tensorflow:Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x7f6292c39f28>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Num'\n",
            "WARNING: Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x7f6292c39f28>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Num'\n",
            "INFO:tensorflow:Done calling model_fn.\n",
            "INFO:tensorflow:Starting evaluation at 2021-02-08T20:33:27Z\n",
            "INFO:tensorflow:Graph was finalized.\n",
            "INFO:tensorflow:Restoring parameters from /tmp/tmp9fc_fqqq/model.ckpt-1200\n",
            "INFO:tensorflow:Running local_init_op.\n",
            "INFO:tensorflow:Done running local_init_op.\n",
            "INFO:tensorflow:Finished evaluation at 2021-02-08-20:33:28\n",
            "INFO:tensorflow:Saving dict for global step 1200: accuracy = 0.85714287, average_loss = 0.36945423, global_step = 1200, loss = 7.7585387\n",
            "INFO:tensorflow:Saving 'checkpoint_path' summary for global step 1200: /tmp/tmp9fc_fqqq/model.ckpt-1200\n",
            "INFO:tensorflow:Calling model_fn.\n",
            "WARNING:tensorflow:Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x7f629a400240>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Num'\n",
            "WARNING: Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x7f629a400240>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Num'\n",
            "INFO:tensorflow:Done calling model_fn.\n",
            "INFO:tensorflow:Starting evaluation at 2021-02-08T20:33:28Z\n",
            "INFO:tensorflow:Graph was finalized.\n",
            "INFO:tensorflow:Restoring parameters from /tmp/tmpq3zds1nw/model.ckpt-1200\n",
            "INFO:tensorflow:Running local_init_op.\n",
            "INFO:tensorflow:Done running local_init_op.\n",
            "INFO:tensorflow:Finished evaluation at 2021-02-08-20:33:29\n",
            "INFO:tensorflow:Saving dict for global step 1200: accuracy = 0.8095238, average_loss = 0.5942747, global_step = 1200, loss = 12.479769\n",
            "INFO:tensorflow:Saving 'checkpoint_path' summary for global step 1200: /tmp/tmpq3zds1nw/model.ckpt-1200\n",
            "INFO:tensorflow:Calling model_fn.\n",
            "WARNING:tensorflow:Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x7f629361f240>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Num'\n",
            "WARNING: Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x7f629361f240>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Num'\n",
            "INFO:tensorflow:Done calling model_fn.\n",
            "INFO:tensorflow:Starting evaluation at 2021-02-08T20:33:29Z\n",
            "INFO:tensorflow:Graph was finalized.\n",
            "INFO:tensorflow:Restoring parameters from /tmp/tmpsp474hw9/model.ckpt-1200\n",
            "INFO:tensorflow:Running local_init_op.\n",
            "INFO:tensorflow:Done running local_init_op.\n",
            "INFO:tensorflow:Finished evaluation at 2021-02-08-20:33:29\n",
            "INFO:tensorflow:Saving dict for global step 1200: accuracy = 0.6666667, average_loss = 0.81080645, global_step = 1200, loss = 17.026936\n",
            "INFO:tensorflow:Saving 'checkpoint_path' summary for global step 1200: /tmp/tmpsp474hw9/model.ckpt-1200\n",
            "INFO:tensorflow:Calling model_fn.\n",
            "WARNING:tensorflow:Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x7f6293361710>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Num'\n",
            "WARNING: Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x7f6293361710>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Num'\n",
            "INFO:tensorflow:Done calling model_fn.\n",
            "INFO:tensorflow:Starting evaluation at 2021-02-08T20:33:30Z\n",
            "INFO:tensorflow:Graph was finalized.\n",
            "INFO:tensorflow:Restoring parameters from /tmp/tmp21k_y2vq/model.ckpt-1200\n",
            "INFO:tensorflow:Running local_init_op.\n",
            "INFO:tensorflow:Done running local_init_op.\n",
            "INFO:tensorflow:Finished evaluation at 2021-02-08-20:33:30\n",
            "INFO:tensorflow:Saving dict for global step 1200: accuracy = 0.7619048, average_loss = 0.7452711, global_step = 1200, loss = 15.650693\n",
            "INFO:tensorflow:Saving 'checkpoint_path' summary for global step 1200: /tmp/tmp21k_y2vq/model.ckpt-1200\n",
            "INFO:tensorflow:Calling model_fn.\n",
            "WARNING:tensorflow:Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x7f62936430f0>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Num'\n",
            "WARNING: Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x7f62936430f0>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Num'\n",
            "INFO:tensorflow:Done calling model_fn.\n",
            "INFO:tensorflow:Starting evaluation at 2021-02-08T20:33:31Z\n",
            "INFO:tensorflow:Graph was finalized.\n",
            "INFO:tensorflow:Restoring parameters from /tmp/tmpbawaa495/model.ckpt-1200\n",
            "INFO:tensorflow:Running local_init_op.\n",
            "INFO:tensorflow:Done running local_init_op.\n",
            "INFO:tensorflow:Finished evaluation at 2021-02-08-20:33:31\n",
            "INFO:tensorflow:Saving dict for global step 1200: accuracy = 0.85714287, average_loss = 0.5789726, global_step = 1200, loss = 12.158424\n",
            "INFO:tensorflow:Saving 'checkpoint_path' summary for global step 1200: /tmp/tmpbawaa495/model.ckpt-1200\n",
            "INFO:tensorflow:Calling model_fn.\n",
            "WARNING:tensorflow:Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x7f6290dea390>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Num'\n",
            "WARNING: Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x7f6290dea390>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Num'\n",
            "INFO:tensorflow:Done calling model_fn.\n",
            "INFO:tensorflow:Starting evaluation at 2021-02-08T20:33:31Z\n",
            "INFO:tensorflow:Graph was finalized.\n",
            "INFO:tensorflow:Restoring parameters from /tmp/tmpsutr6jvb/model.ckpt-1200\n",
            "INFO:tensorflow:Running local_init_op.\n",
            "INFO:tensorflow:Done running local_init_op.\n",
            "INFO:tensorflow:Finished evaluation at 2021-02-08-20:33:32\n",
            "INFO:tensorflow:Saving dict for global step 1200: accuracy = 0.7619048, average_loss = 0.86179876, global_step = 1200, loss = 18.097775\n",
            "INFO:tensorflow:Saving 'checkpoint_path' summary for global step 1200: /tmp/tmpsutr6jvb/model.ckpt-1200\n",
            "INFO:tensorflow:Calling model_fn.\n",
            "WARNING:tensorflow:Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x7f6290c28160>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Num'\n",
            "WARNING: Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x7f6290c28160>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Num'\n",
            "INFO:tensorflow:Done calling model_fn.\n",
            "INFO:tensorflow:Starting evaluation at 2021-02-08T20:33:32Z\n",
            "INFO:tensorflow:Graph was finalized.\n",
            "INFO:tensorflow:Restoring parameters from /tmp/tmpd33urkpe/model.ckpt-1200\n",
            "INFO:tensorflow:Running local_init_op.\n",
            "INFO:tensorflow:Done running local_init_op.\n",
            "INFO:tensorflow:Finished evaluation at 2021-02-08-20:33:32\n",
            "INFO:tensorflow:Saving dict for global step 1200: accuracy = 0.7619048, average_loss = 0.7818747, global_step = 1200, loss = 16.419369\n",
            "INFO:tensorflow:Saving 'checkpoint_path' summary for global step 1200: /tmp/tmpd33urkpe/model.ckpt-1200\n",
            "INFO:tensorflow:Calling model_fn.\n",
            "WARNING:tensorflow:Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x7f629102d748>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Num'\n",
            "WARNING: Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x7f629102d748>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Num'\n",
            "INFO:tensorflow:Done calling model_fn.\n",
            "INFO:tensorflow:Starting evaluation at 2021-02-08T20:33:33Z\n",
            "INFO:tensorflow:Graph was finalized.\n",
            "INFO:tensorflow:Restoring parameters from /tmp/tmphum8zuff/model.ckpt-1200\n",
            "INFO:tensorflow:Running local_init_op.\n",
            "INFO:tensorflow:Done running local_init_op.\n",
            "INFO:tensorflow:Finished evaluation at 2021-02-08-20:33:34\n",
            "INFO:tensorflow:Saving dict for global step 1200: accuracy = 0.6666667, average_loss = 0.9313924, global_step = 1200, loss = 19.55924\n",
            "INFO:tensorflow:Saving 'checkpoint_path' summary for global step 1200: /tmp/tmphum8zuff/model.ckpt-1200\n",
            "INFO:tensorflow:Calling model_fn.\n",
            "WARNING:tensorflow:Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x7f6290cc14e0>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Num'\n",
            "WARNING: Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x7f6290cc14e0>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Num'\n",
            "INFO:tensorflow:Done calling model_fn.\n",
            "INFO:tensorflow:Starting evaluation at 2021-02-08T20:33:34Z\n",
            "INFO:tensorflow:Graph was finalized.\n",
            "INFO:tensorflow:Restoring parameters from /tmp/tmpenrrglss/model.ckpt-1200\n",
            "INFO:tensorflow:Running local_init_op.\n",
            "INFO:tensorflow:Done running local_init_op.\n",
            "INFO:tensorflow:Finished evaluation at 2021-02-08-20:33:34\n",
            "INFO:tensorflow:Saving dict for global step 1200: accuracy = 0.71428573, average_loss = 0.5051062, global_step = 1200, loss = 10.60723\n",
            "INFO:tensorflow:Saving 'checkpoint_path' summary for global step 1200: /tmp/tmpenrrglss/model.ckpt-1200\n",
            "INFO:tensorflow:Calling model_fn.\n",
            "WARNING:tensorflow:Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x7f6292e57860>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Num'\n",
            "WARNING: Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x7f6292e57860>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Num'\n",
            "INFO:tensorflow:Done calling model_fn.\n",
            "INFO:tensorflow:Starting evaluation at 2021-02-08T20:33:35Z\n",
            "INFO:tensorflow:Graph was finalized.\n",
            "INFO:tensorflow:Restoring parameters from /tmp/tmpbe3d820j/model.ckpt-1200\n",
            "INFO:tensorflow:Running local_init_op.\n",
            "INFO:tensorflow:Done running local_init_op.\n",
            "INFO:tensorflow:Finished evaluation at 2021-02-08-20:33:35\n",
            "INFO:tensorflow:Saving dict for global step 1200: accuracy = 0.8095238, average_loss = 0.8094966, global_step = 1200, loss = 16.999428\n",
            "INFO:tensorflow:Saving 'checkpoint_path' summary for global step 1200: /tmp/tmpbe3d820j/model.ckpt-1200\n",
            "INFO:tensorflow:Calling model_fn.\n",
            "WARNING:tensorflow:Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x7f62913bd7b8>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Num'\n",
            "WARNING: Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x7f62913bd7b8>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Num'\n",
            "INFO:tensorflow:Done calling model_fn.\n",
            "INFO:tensorflow:Starting evaluation at 2021-02-08T20:33:36Z\n",
            "INFO:tensorflow:Graph was finalized.\n",
            "INFO:tensorflow:Restoring parameters from /tmp/tmp29o4btp1/model.ckpt-1200\n",
            "INFO:tensorflow:Running local_init_op.\n",
            "INFO:tensorflow:Done running local_init_op.\n",
            "INFO:tensorflow:Finished evaluation at 2021-02-08-20:33:36\n",
            "INFO:tensorflow:Saving dict for global step 1200: accuracy = 0.85714287, average_loss = 0.60053635, global_step = 1200, loss = 12.611263\n",
            "INFO:tensorflow:Saving 'checkpoint_path' summary for global step 1200: /tmp/tmp29o4btp1/model.ckpt-1200\n",
            "INFO:tensorflow:Calling model_fn.\n",
            "WARNING:tensorflow:Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x7f6291209dd8>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Num'\n",
            "WARNING: Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x7f6291209dd8>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Num'\n",
            "INFO:tensorflow:Done calling model_fn.\n",
            "INFO:tensorflow:Starting evaluation at 2021-02-08T20:33:36Z\n",
            "INFO:tensorflow:Graph was finalized.\n",
            "INFO:tensorflow:Restoring parameters from /tmp/tmpfskvae1c/model.ckpt-1200\n",
            "INFO:tensorflow:Running local_init_op.\n",
            "INFO:tensorflow:Done running local_init_op.\n",
            "INFO:tensorflow:Finished evaluation at 2021-02-08-20:33:37\n",
            "INFO:tensorflow:Saving dict for global step 1200: accuracy = 0.8095238, average_loss = 0.45126158, global_step = 1200, loss = 9.476493\n",
            "INFO:tensorflow:Saving 'checkpoint_path' summary for global step 1200: /tmp/tmpfskvae1c/model.ckpt-1200\n",
            "INFO:tensorflow:Calling model_fn.\n",
            "WARNING:tensorflow:Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x7f6291215ac8>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Num'\n",
            "WARNING: Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x7f6291215ac8>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Num'\n",
            "INFO:tensorflow:Done calling model_fn.\n",
            "INFO:tensorflow:Starting evaluation at 2021-02-08T20:33:37Z\n",
            "INFO:tensorflow:Graph was finalized.\n",
            "INFO:tensorflow:Restoring parameters from /tmp/tmp4u5d1v9s/model.ckpt-1200\n",
            "INFO:tensorflow:Running local_init_op.\n",
            "INFO:tensorflow:Done running local_init_op.\n",
            "INFO:tensorflow:Finished evaluation at 2021-02-08-20:33:37\n",
            "INFO:tensorflow:Saving dict for global step 1200: accuracy = 0.8095238, average_loss = 0.8356689, global_step = 1200, loss = 17.549047\n",
            "INFO:tensorflow:Saving 'checkpoint_path' summary for global step 1200: /tmp/tmp4u5d1v9s/model.ckpt-1200\n",
            "INFO:tensorflow:Calling model_fn.\n",
            "WARNING:tensorflow:Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x7f6292d0df28>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Num'\n",
            "WARNING: Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x7f6292d0df28>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Num'\n",
            "INFO:tensorflow:Done calling model_fn.\n",
            "INFO:tensorflow:Starting evaluation at 2021-02-08T20:33:38Z\n",
            "INFO:tensorflow:Graph was finalized.\n",
            "INFO:tensorflow:Restoring parameters from /tmp/tmphw8czze6/model.ckpt-1200\n",
            "INFO:tensorflow:Running local_init_op.\n",
            "INFO:tensorflow:Done running local_init_op.\n",
            "INFO:tensorflow:Finished evaluation at 2021-02-08-20:33:38\n",
            "INFO:tensorflow:Saving dict for global step 1200: accuracy = 0.8095238, average_loss = 0.7100989, global_step = 1200, loss = 14.912078\n",
            "INFO:tensorflow:Saving 'checkpoint_path' summary for global step 1200: /tmp/tmphw8czze6/model.ckpt-1200\n",
            "INFO:tensorflow:Calling model_fn.\n",
            "WARNING:tensorflow:Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x7f6292e92048>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Num'\n",
            "WARNING: Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x7f6292e92048>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Num'\n",
            "INFO:tensorflow:Done calling model_fn.\n",
            "INFO:tensorflow:Starting evaluation at 2021-02-08T20:33:39Z\n",
            "INFO:tensorflow:Graph was finalized.\n",
            "INFO:tensorflow:Restoring parameters from /tmp/tmp3f88_882/model.ckpt-1200\n",
            "INFO:tensorflow:Running local_init_op.\n",
            "INFO:tensorflow:Done running local_init_op.\n",
            "INFO:tensorflow:Finished evaluation at 2021-02-08-20:33:39\n",
            "INFO:tensorflow:Saving dict for global step 1200: accuracy = 0.8095238, average_loss = 0.6018033, global_step = 1200, loss = 12.63787\n",
            "INFO:tensorflow:Saving 'checkpoint_path' summary for global step 1200: /tmp/tmp3f88_882/model.ckpt-1200\n",
            "INFO:tensorflow:Calling model_fn.\n",
            "WARNING:tensorflow:Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x7f6291301ac8>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Num'\n",
            "WARNING: Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x7f6291301ac8>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Num'\n",
            "INFO:tensorflow:Done calling model_fn.\n",
            "INFO:tensorflow:Starting evaluation at 2021-02-08T20:33:39Z\n",
            "INFO:tensorflow:Graph was finalized.\n",
            "INFO:tensorflow:Restoring parameters from /tmp/tmpo8nvehc0/model.ckpt-1200\n",
            "INFO:tensorflow:Running local_init_op.\n",
            "INFO:tensorflow:Done running local_init_op.\n",
            "INFO:tensorflow:Finished evaluation at 2021-02-08-20:33:40\n",
            "INFO:tensorflow:Saving dict for global step 1200: accuracy = 0.85714287, average_loss = 0.3746635, global_step = 1200, loss = 7.8679333\n",
            "INFO:tensorflow:Saving 'checkpoint_path' summary for global step 1200: /tmp/tmpo8nvehc0/model.ckpt-1200\n",
            "INFO:tensorflow:Calling model_fn.\n",
            "WARNING:tensorflow:Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x7f6290e3ed68>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Num'\n",
            "WARNING: Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x7f6290e3ed68>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Num'\n",
            "INFO:tensorflow:Done calling model_fn.\n",
            "INFO:tensorflow:Starting evaluation at 2021-02-08T20:33:40Z\n",
            "INFO:tensorflow:Graph was finalized.\n",
            "INFO:tensorflow:Restoring parameters from /tmp/tmp__cgl3ub/model.ckpt-1200\n",
            "INFO:tensorflow:Running local_init_op.\n",
            "INFO:tensorflow:Done running local_init_op.\n",
            "INFO:tensorflow:Finished evaluation at 2021-02-08-20:33:41\n",
            "INFO:tensorflow:Saving dict for global step 1200: accuracy = 0.5714286, average_loss = 0.77214843, global_step = 1200, loss = 16.215117\n",
            "INFO:tensorflow:Saving 'checkpoint_path' summary for global step 1200: /tmp/tmp__cgl3ub/model.ckpt-1200\n",
            "INFO:tensorflow:Calling model_fn.\n",
            "WARNING:tensorflow:Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x7f6290eeecf8>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Num'\n",
            "WARNING: Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x7f6290eeecf8>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Num'\n",
            "INFO:tensorflow:Done calling model_fn.\n",
            "INFO:tensorflow:Starting evaluation at 2021-02-08T20:33:41Z\n",
            "INFO:tensorflow:Graph was finalized.\n",
            "INFO:tensorflow:Restoring parameters from /tmp/tmpa0ofh0pk/model.ckpt-1200\n",
            "INFO:tensorflow:Running local_init_op.\n",
            "INFO:tensorflow:Done running local_init_op.\n",
            "INFO:tensorflow:Finished evaluation at 2021-02-08-20:33:42\n",
            "INFO:tensorflow:Saving dict for global step 1200: accuracy = 0.5714286, average_loss = 0.80330306, global_step = 1200, loss = 16.869364\n",
            "INFO:tensorflow:Saving 'checkpoint_path' summary for global step 1200: /tmp/tmpa0ofh0pk/model.ckpt-1200\n",
            "INFO:tensorflow:Calling model_fn.\n",
            "WARNING:tensorflow:Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x7f62936052b0>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Num'\n",
            "WARNING: Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x7f62936052b0>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Num'\n",
            "INFO:tensorflow:Done calling model_fn.\n",
            "INFO:tensorflow:Starting evaluation at 2021-02-08T20:33:42Z\n",
            "INFO:tensorflow:Graph was finalized.\n",
            "INFO:tensorflow:Restoring parameters from /tmp/tmpn_u0b92d/model.ckpt-1200\n",
            "INFO:tensorflow:Running local_init_op.\n",
            "INFO:tensorflow:Done running local_init_op.\n",
            "INFO:tensorflow:Finished evaluation at 2021-02-08-20:33:42\n",
            "INFO:tensorflow:Saving dict for global step 1200: accuracy = 0.8095238, average_loss = 0.5996551, global_step = 1200, loss = 12.592757\n",
            "INFO:tensorflow:Saving 'checkpoint_path' summary for global step 1200: /tmp/tmpn_u0b92d/model.ckpt-1200\n",
            "INFO:tensorflow:Calling model_fn.\n",
            "WARNING:tensorflow:Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x7f62934258d0>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Num'\n",
            "WARNING: Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x7f62934258d0>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Num'\n",
            "INFO:tensorflow:Done calling model_fn.\n",
            "INFO:tensorflow:Starting evaluation at 2021-02-08T20:33:43Z\n",
            "INFO:tensorflow:Graph was finalized.\n",
            "INFO:tensorflow:Restoring parameters from /tmp/tmpr1f2q8b6/model.ckpt-1200\n",
            "INFO:tensorflow:Running local_init_op.\n",
            "INFO:tensorflow:Done running local_init_op.\n",
            "INFO:tensorflow:Finished evaluation at 2021-02-08-20:33:43\n",
            "INFO:tensorflow:Saving dict for global step 1200: accuracy = 0.8095238, average_loss = 0.69439507, global_step = 1200, loss = 14.582296\n",
            "INFO:tensorflow:Saving 'checkpoint_path' summary for global step 1200: /tmp/tmpr1f2q8b6/model.ckpt-1200\n",
            "INFO:tensorflow:Calling model_fn.\n",
            "WARNING:tensorflow:Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x7f629363a240>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Num'\n",
            "WARNING: Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x7f629363a240>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Num'\n",
            "INFO:tensorflow:Done calling model_fn.\n",
            "INFO:tensorflow:Starting evaluation at 2021-02-08T20:33:44Z\n",
            "INFO:tensorflow:Graph was finalized.\n",
            "INFO:tensorflow:Restoring parameters from /tmp/tmpoggpqhod/model.ckpt-1200\n",
            "INFO:tensorflow:Running local_init_op.\n",
            "INFO:tensorflow:Done running local_init_op.\n",
            "INFO:tensorflow:Finished evaluation at 2021-02-08-20:33:44\n",
            "INFO:tensorflow:Saving dict for global step 1200: accuracy = 0.71428573, average_loss = 0.70749074, global_step = 1200, loss = 14.857306\n",
            "INFO:tensorflow:Saving 'checkpoint_path' summary for global step 1200: /tmp/tmpoggpqhod/model.ckpt-1200\n",
            "INFO:tensorflow:Calling model_fn.\n",
            "WARNING:tensorflow:Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x7f628aa83cc0>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Num'\n",
            "WARNING: Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x7f628aa83cc0>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Num'\n",
            "INFO:tensorflow:Done calling model_fn.\n",
            "INFO:tensorflow:Starting evaluation at 2021-02-08T20:33:44Z\n",
            "INFO:tensorflow:Graph was finalized.\n",
            "INFO:tensorflow:Restoring parameters from /tmp/tmpxmrkifdi/model.ckpt-1200\n",
            "INFO:tensorflow:Running local_init_op.\n",
            "INFO:tensorflow:Done running local_init_op.\n",
            "INFO:tensorflow:Finished evaluation at 2021-02-08-20:33:45\n",
            "INFO:tensorflow:Saving dict for global step 1200: accuracy = 0.8095238, average_loss = 0.5193439, global_step = 1200, loss = 10.906222\n",
            "INFO:tensorflow:Saving 'checkpoint_path' summary for global step 1200: /tmp/tmpxmrkifdi/model.ckpt-1200\n",
            "INFO:tensorflow:Calling model_fn.\n",
            "WARNING:tensorflow:Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x7f62931e6588>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Num'\n",
            "WARNING: Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x7f62931e6588>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Num'\n",
            "INFO:tensorflow:Done calling model_fn.\n",
            "INFO:tensorflow:Starting evaluation at 2021-02-08T20:33:45Z\n",
            "INFO:tensorflow:Graph was finalized.\n",
            "INFO:tensorflow:Restoring parameters from /tmp/tmpfkvdwa3w/model.ckpt-1200\n",
            "INFO:tensorflow:Running local_init_op.\n",
            "INFO:tensorflow:Done running local_init_op.\n",
            "INFO:tensorflow:Finished evaluation at 2021-02-08-20:33:46\n",
            "INFO:tensorflow:Saving dict for global step 1200: accuracy = 0.7619048, average_loss = 0.6041272, global_step = 1200, loss = 12.686671\n",
            "INFO:tensorflow:Saving 'checkpoint_path' summary for global step 1200: /tmp/tmpfkvdwa3w/model.ckpt-1200\n",
            "INFO:tensorflow:Calling model_fn.\n",
            "WARNING:tensorflow:Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x7f629115fba8>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Num'\n",
            "WARNING: Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x7f629115fba8>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Num'\n",
            "INFO:tensorflow:Done calling model_fn.\n",
            "INFO:tensorflow:Starting evaluation at 2021-02-08T20:33:46Z\n",
            "INFO:tensorflow:Graph was finalized.\n",
            "INFO:tensorflow:Restoring parameters from /tmp/tmpjdsmp_wn/model.ckpt-1200\n",
            "INFO:tensorflow:Running local_init_op.\n",
            "INFO:tensorflow:Done running local_init_op.\n",
            "INFO:tensorflow:Finished evaluation at 2021-02-08-20:33:46\n",
            "INFO:tensorflow:Saving dict for global step 1200: accuracy = 0.61904764, average_loss = 0.63305146, global_step = 1200, loss = 13.294081\n",
            "INFO:tensorflow:Saving 'checkpoint_path' summary for global step 1200: /tmp/tmpjdsmp_wn/model.ckpt-1200\n",
            "INFO:tensorflow:Calling model_fn.\n",
            "WARNING:tensorflow:Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x7f6292f02eb8>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Num'\n",
            "WARNING: Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x7f6292f02eb8>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Num'\n",
            "INFO:tensorflow:Done calling model_fn.\n",
            "INFO:tensorflow:Starting evaluation at 2021-02-08T20:33:47Z\n",
            "INFO:tensorflow:Graph was finalized.\n",
            "INFO:tensorflow:Restoring parameters from /tmp/tmpu0kna8ze/model.ckpt-1200\n",
            "INFO:tensorflow:Running local_init_op.\n",
            "INFO:tensorflow:Done running local_init_op.\n",
            "INFO:tensorflow:Finished evaluation at 2021-02-08-20:33:47\n",
            "INFO:tensorflow:Saving dict for global step 1200: accuracy = 0.85714287, average_loss = 0.43588084, global_step = 1200, loss = 9.153498\n",
            "INFO:tensorflow:Saving 'checkpoint_path' summary for global step 1200: /tmp/tmpu0kna8ze/model.ckpt-1200\n",
            "INFO:tensorflow:Calling model_fn.\n",
            "WARNING:tensorflow:Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x7f6290eea320>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Num'\n",
            "WARNING: Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x7f6290eea320>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Num'\n",
            "INFO:tensorflow:Done calling model_fn.\n",
            "INFO:tensorflow:Starting evaluation at 2021-02-08T20:33:48Z\n",
            "INFO:tensorflow:Graph was finalized.\n",
            "INFO:tensorflow:Restoring parameters from /tmp/tmpayt7d236/model.ckpt-1200\n",
            "INFO:tensorflow:Running local_init_op.\n",
            "INFO:tensorflow:Done running local_init_op.\n",
            "INFO:tensorflow:Finished evaluation at 2021-02-08-20:33:48\n",
            "INFO:tensorflow:Saving dict for global step 1200: accuracy = 0.8095238, average_loss = 0.6364301, global_step = 1200, loss = 13.365031\n",
            "INFO:tensorflow:Saving 'checkpoint_path' summary for global step 1200: /tmp/tmpayt7d236/model.ckpt-1200\n",
            "INFO:tensorflow:Calling model_fn.\n",
            "WARNING:tensorflow:Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x7f6292ce48d0>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Num'\n",
            "WARNING: Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x7f6292ce48d0>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Num'\n",
            "INFO:tensorflow:Done calling model_fn.\n",
            "INFO:tensorflow:Starting evaluation at 2021-02-08T20:33:49Z\n",
            "INFO:tensorflow:Graph was finalized.\n",
            "INFO:tensorflow:Restoring parameters from /tmp/tmpairvriz1/model.ckpt-1200\n",
            "INFO:tensorflow:Running local_init_op.\n",
            "INFO:tensorflow:Done running local_init_op.\n",
            "INFO:tensorflow:Finished evaluation at 2021-02-08-20:33:49\n",
            "INFO:tensorflow:Saving dict for global step 1200: accuracy = 0.85714287, average_loss = 0.43264893, global_step = 1200, loss = 9.085628\n",
            "INFO:tensorflow:Saving 'checkpoint_path' summary for global step 1200: /tmp/tmpairvriz1/model.ckpt-1200\n",
            "INFO:tensorflow:Calling model_fn.\n",
            "WARNING:tensorflow:Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x7f629a3a3828>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Num'\n",
            "WARNING: Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x7f629a3a3828>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Num'\n",
            "INFO:tensorflow:Done calling model_fn.\n",
            "INFO:tensorflow:Starting evaluation at 2021-02-08T20:33:49Z\n",
            "INFO:tensorflow:Graph was finalized.\n",
            "INFO:tensorflow:Restoring parameters from /tmp/tmputongol7/model.ckpt-1200\n",
            "INFO:tensorflow:Running local_init_op.\n",
            "INFO:tensorflow:Done running local_init_op.\n",
            "INFO:tensorflow:Finished evaluation at 2021-02-08-20:33:50\n",
            "INFO:tensorflow:Saving dict for global step 1200: accuracy = 0.8095238, average_loss = 0.64912766, global_step = 1200, loss = 13.631681\n",
            "INFO:tensorflow:Saving 'checkpoint_path' summary for global step 1200: /tmp/tmputongol7/model.ckpt-1200\n",
            "INFO:tensorflow:Calling model_fn.\n",
            "WARNING:tensorflow:Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x7f62933c9b70>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Num'\n",
            "WARNING: Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x7f62933c9b70>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Num'\n",
            "INFO:tensorflow:Done calling model_fn.\n",
            "INFO:tensorflow:Starting evaluation at 2021-02-08T20:33:50Z\n",
            "INFO:tensorflow:Graph was finalized.\n",
            "INFO:tensorflow:Restoring parameters from /tmp/tmpcmfuexel/model.ckpt-1200\n",
            "INFO:tensorflow:Running local_init_op.\n",
            "INFO:tensorflow:Done running local_init_op.\n",
            "INFO:tensorflow:Finished evaluation at 2021-02-08-20:33:50\n",
            "INFO:tensorflow:Saving dict for global step 1200: accuracy = 0.6666667, average_loss = 1.0138481, global_step = 1200, loss = 21.29081\n",
            "INFO:tensorflow:Saving 'checkpoint_path' summary for global step 1200: /tmp/tmpcmfuexel/model.ckpt-1200\n",
            "INFO:tensorflow:Calling model_fn.\n",
            "WARNING:tensorflow:Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x7f6290e9ddd8>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Num'\n",
            "WARNING: Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x7f6290e9ddd8>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Num'\n",
            "INFO:tensorflow:Done calling model_fn.\n",
            "INFO:tensorflow:Starting evaluation at 2021-02-08T20:33:51Z\n",
            "INFO:tensorflow:Graph was finalized.\n",
            "INFO:tensorflow:Restoring parameters from /tmp/tmpwesnmjge/model.ckpt-1200\n",
            "INFO:tensorflow:Running local_init_op.\n",
            "INFO:tensorflow:Done running local_init_op.\n",
            "INFO:tensorflow:Finished evaluation at 2021-02-08-20:33:51\n",
            "INFO:tensorflow:Saving dict for global step 1200: accuracy = 0.8095238, average_loss = 0.59838694, global_step = 1200, loss = 12.566126\n",
            "INFO:tensorflow:Saving 'checkpoint_path' summary for global step 1200: /tmp/tmpwesnmjge/model.ckpt-1200\n",
            "INFO:tensorflow:Calling model_fn.\n",
            "WARNING:tensorflow:Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x7f6293037048>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Num'\n",
            "WARNING: Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x7f6293037048>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Num'\n",
            "INFO:tensorflow:Done calling model_fn.\n",
            "INFO:tensorflow:Starting evaluation at 2021-02-08T20:33:52Z\n",
            "INFO:tensorflow:Graph was finalized.\n",
            "INFO:tensorflow:Restoring parameters from /tmp/tmp_ci5ljbs/model.ckpt-1200\n",
            "INFO:tensorflow:Running local_init_op.\n",
            "INFO:tensorflow:Done running local_init_op.\n",
            "INFO:tensorflow:Finished evaluation at 2021-02-08-20:33:52\n",
            "INFO:tensorflow:Saving dict for global step 1200: accuracy = 0.61904764, average_loss = 0.73871034, global_step = 1200, loss = 15.5129175\n",
            "INFO:tensorflow:Saving 'checkpoint_path' summary for global step 1200: /tmp/tmp_ci5ljbs/model.ckpt-1200\n",
            "INFO:tensorflow:Calling model_fn.\n",
            "WARNING:tensorflow:Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x7f6292e90668>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Num'\n",
            "WARNING: Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x7f6292e90668>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Num'\n",
            "INFO:tensorflow:Done calling model_fn.\n",
            "INFO:tensorflow:Starting evaluation at 2021-02-08T20:33:52Z\n",
            "INFO:tensorflow:Graph was finalized.\n",
            "INFO:tensorflow:Restoring parameters from /tmp/tmplpistkcz/model.ckpt-1200\n",
            "INFO:tensorflow:Running local_init_op.\n",
            "INFO:tensorflow:Done running local_init_op.\n",
            "INFO:tensorflow:Finished evaluation at 2021-02-08-20:33:53\n",
            "INFO:tensorflow:Saving dict for global step 1200: accuracy = 0.8095238, average_loss = 0.8672718, global_step = 1200, loss = 18.212708\n",
            "INFO:tensorflow:Saving 'checkpoint_path' summary for global step 1200: /tmp/tmplpistkcz/model.ckpt-1200\n",
            "INFO:tensorflow:Calling model_fn.\n",
            "WARNING:tensorflow:Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x7f6293220390>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Num'\n",
            "WARNING: Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x7f6293220390>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Num'\n",
            "INFO:tensorflow:Done calling model_fn.\n",
            "INFO:tensorflow:Starting evaluation at 2021-02-08T20:33:53Z\n",
            "INFO:tensorflow:Graph was finalized.\n",
            "INFO:tensorflow:Restoring parameters from /tmp/tmp5d5s5ah3/model.ckpt-1200\n",
            "INFO:tensorflow:Running local_init_op.\n",
            "INFO:tensorflow:Done running local_init_op.\n",
            "INFO:tensorflow:Finished evaluation at 2021-02-08-20:33:54\n",
            "INFO:tensorflow:Saving dict for global step 1200: accuracy = 0.8095238, average_loss = 0.60312533, global_step = 1200, loss = 12.665632\n",
            "INFO:tensorflow:Saving 'checkpoint_path' summary for global step 1200: /tmp/tmp5d5s5ah3/model.ckpt-1200\n",
            "INFO:tensorflow:Calling model_fn.\n",
            "WARNING:tensorflow:Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x7f6290c9a470>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Num'\n",
            "WARNING: Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x7f6290c9a470>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Num'\n",
            "INFO:tensorflow:Done calling model_fn.\n",
            "INFO:tensorflow:Starting evaluation at 2021-02-08T20:33:54Z\n",
            "INFO:tensorflow:Graph was finalized.\n",
            "INFO:tensorflow:Restoring parameters from /tmp/tmpojb1nxz0/model.ckpt-1200\n",
            "INFO:tensorflow:Running local_init_op.\n",
            "INFO:tensorflow:Done running local_init_op.\n",
            "INFO:tensorflow:Finished evaluation at 2021-02-08-20:33:54\n",
            "INFO:tensorflow:Saving dict for global step 1200: accuracy = 0.85714287, average_loss = 0.4870686, global_step = 1200, loss = 10.22844\n",
            "INFO:tensorflow:Saving 'checkpoint_path' summary for global step 1200: /tmp/tmpojb1nxz0/model.ckpt-1200\n",
            "INFO:tensorflow:Calling model_fn.\n",
            "WARNING:tensorflow:Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x7f62912c45f8>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Num'\n",
            "WARNING: Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x7f62912c45f8>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Num'\n",
            "INFO:tensorflow:Done calling model_fn.\n",
            "INFO:tensorflow:Starting evaluation at 2021-02-08T20:33:55Z\n",
            "INFO:tensorflow:Graph was finalized.\n",
            "INFO:tensorflow:Restoring parameters from /tmp/tmpcn2z0gkq/model.ckpt-1200\n",
            "INFO:tensorflow:Running local_init_op.\n",
            "INFO:tensorflow:Done running local_init_op.\n",
            "INFO:tensorflow:Finished evaluation at 2021-02-08-20:33:55\n",
            "INFO:tensorflow:Saving dict for global step 1200: accuracy = 0.8095238, average_loss = 0.57239574, global_step = 1200, loss = 12.02031\n",
            "INFO:tensorflow:Saving 'checkpoint_path' summary for global step 1200: /tmp/tmpcn2z0gkq/model.ckpt-1200\n",
            "INFO:tensorflow:Calling model_fn.\n",
            "WARNING:tensorflow:Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x7f6290f5b9e8>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Num'\n",
            "WARNING: Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x7f6290f5b9e8>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Num'\n",
            "INFO:tensorflow:Done calling model_fn.\n",
            "INFO:tensorflow:Starting evaluation at 2021-02-08T20:33:56Z\n",
            "INFO:tensorflow:Graph was finalized.\n",
            "INFO:tensorflow:Restoring parameters from /tmp/tmpef0wf7t2/model.ckpt-1200\n",
            "INFO:tensorflow:Running local_init_op.\n",
            "INFO:tensorflow:Done running local_init_op.\n",
            "INFO:tensorflow:Finished evaluation at 2021-02-08-20:33:56\n",
            "INFO:tensorflow:Saving dict for global step 1200: accuracy = 0.8095238, average_loss = 0.5901567, global_step = 1200, loss = 12.3932905\n",
            "INFO:tensorflow:Saving 'checkpoint_path' summary for global step 1200: /tmp/tmpef0wf7t2/model.ckpt-1200\n",
            "INFO:tensorflow:Calling model_fn.\n",
            "WARNING:tensorflow:Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x7f6292bccd30>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Num'\n",
            "WARNING: Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x7f6292bccd30>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Num'\n",
            "INFO:tensorflow:Done calling model_fn.\n",
            "INFO:tensorflow:Starting evaluation at 2021-02-08T20:33:57Z\n",
            "INFO:tensorflow:Graph was finalized.\n",
            "INFO:tensorflow:Restoring parameters from /tmp/tmpfdkl5wbv/model.ckpt-1200\n",
            "INFO:tensorflow:Running local_init_op.\n",
            "INFO:tensorflow:Done running local_init_op.\n",
            "INFO:tensorflow:Finished evaluation at 2021-02-08-20:33:57\n",
            "INFO:tensorflow:Saving dict for global step 1200: accuracy = 0.85714287, average_loss = 0.38026682, global_step = 1200, loss = 7.9856033\n",
            "INFO:tensorflow:Saving 'checkpoint_path' summary for global step 1200: /tmp/tmpfdkl5wbv/model.ckpt-1200\n",
            "INFO:tensorflow:Calling model_fn.\n",
            "WARNING:tensorflow:Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x7f6290d752e8>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Num'\n",
            "WARNING: Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x7f6290d752e8>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Num'\n",
            "INFO:tensorflow:Done calling model_fn.\n",
            "INFO:tensorflow:Starting evaluation at 2021-02-08T20:33:58Z\n",
            "INFO:tensorflow:Graph was finalized.\n",
            "INFO:tensorflow:Restoring parameters from /tmp/tmp4xq6cqo3/model.ckpt-1200\n",
            "INFO:tensorflow:Running local_init_op.\n",
            "INFO:tensorflow:Done running local_init_op.\n",
            "INFO:tensorflow:Finished evaluation at 2021-02-08-20:33:58\n",
            "INFO:tensorflow:Saving dict for global step 1200: accuracy = 0.71428573, average_loss = 0.45016208, global_step = 1200, loss = 9.453403\n",
            "INFO:tensorflow:Saving 'checkpoint_path' summary for global step 1200: /tmp/tmp4xq6cqo3/model.ckpt-1200\n",
            "INFO:tensorflow:Calling model_fn.\n",
            "WARNING:tensorflow:Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x7f629116d5c0>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Num'\n",
            "WARNING: Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x7f629116d5c0>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Num'\n",
            "INFO:tensorflow:Done calling model_fn.\n",
            "INFO:tensorflow:Starting evaluation at 2021-02-08T20:33:58Z\n",
            "INFO:tensorflow:Graph was finalized.\n",
            "INFO:tensorflow:Restoring parameters from /tmp/tmpxflpm2w7/model.ckpt-1200\n",
            "INFO:tensorflow:Running local_init_op.\n",
            "INFO:tensorflow:Done running local_init_op.\n",
            "INFO:tensorflow:Finished evaluation at 2021-02-08-20:33:59\n",
            "INFO:tensorflow:Saving dict for global step 1200: accuracy = 0.7619048, average_loss = 0.6342949, global_step = 1200, loss = 13.320193\n",
            "INFO:tensorflow:Saving 'checkpoint_path' summary for global step 1200: /tmp/tmpxflpm2w7/model.ckpt-1200\n",
            "INFO:tensorflow:Calling model_fn.\n",
            "WARNING:tensorflow:Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x7f629b5f3668>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Num'\n",
            "WARNING: Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x7f629b5f3668>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Num'\n",
            "INFO:tensorflow:Done calling model_fn.\n",
            "INFO:tensorflow:Starting evaluation at 2021-02-08T20:33:59Z\n",
            "INFO:tensorflow:Graph was finalized.\n",
            "INFO:tensorflow:Restoring parameters from /tmp/tmp45qr1a5r/model.ckpt-1200\n",
            "INFO:tensorflow:Running local_init_op.\n",
            "INFO:tensorflow:Done running local_init_op.\n",
            "INFO:tensorflow:Finished evaluation at 2021-02-08-20:33:59\n",
            "INFO:tensorflow:Saving dict for global step 1200: accuracy = 0.8095238, average_loss = 0.62745124, global_step = 1200, loss = 13.1764765\n",
            "INFO:tensorflow:Saving 'checkpoint_path' summary for global step 1200: /tmp/tmp45qr1a5r/model.ckpt-1200\n",
            "INFO:tensorflow:Calling model_fn.\n",
            "WARNING:tensorflow:Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x7f628b30b470>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Num'\n",
            "WARNING: Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x7f628b30b470>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Num'\n",
            "INFO:tensorflow:Done calling model_fn.\n",
            "INFO:tensorflow:Starting evaluation at 2021-02-08T20:34:00Z\n",
            "INFO:tensorflow:Graph was finalized.\n",
            "INFO:tensorflow:Restoring parameters from /tmp/tmptligya6b/model.ckpt-1200\n",
            "INFO:tensorflow:Running local_init_op.\n",
            "INFO:tensorflow:Done running local_init_op.\n",
            "INFO:tensorflow:Finished evaluation at 2021-02-08-20:34:00\n",
            "INFO:tensorflow:Saving dict for global step 1200: accuracy = 0.8095238, average_loss = 0.7829658, global_step = 1200, loss = 16.442282\n",
            "INFO:tensorflow:Saving 'checkpoint_path' summary for global step 1200: /tmp/tmptligya6b/model.ckpt-1200\n",
            "INFO:tensorflow:Calling model_fn.\n",
            "WARNING:tensorflow:Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x7f629137b2b0>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Num'\n",
            "WARNING: Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x7f629137b2b0>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Num'\n",
            "INFO:tensorflow:Done calling model_fn.\n",
            "INFO:tensorflow:Starting evaluation at 2021-02-08T20:34:01Z\n",
            "INFO:tensorflow:Graph was finalized.\n",
            "INFO:tensorflow:Restoring parameters from /tmp/tmp8yee0f8m/model.ckpt-1200\n",
            "INFO:tensorflow:Running local_init_op.\n",
            "INFO:tensorflow:Done running local_init_op.\n",
            "INFO:tensorflow:Finished evaluation at 2021-02-08-20:34:01\n",
            "INFO:tensorflow:Saving dict for global step 1200: accuracy = 0.8095238, average_loss = 0.5484456, global_step = 1200, loss = 11.517358\n",
            "INFO:tensorflow:Saving 'checkpoint_path' summary for global step 1200: /tmp/tmp8yee0f8m/model.ckpt-1200\n",
            "INFO:tensorflow:Calling model_fn.\n",
            "WARNING:tensorflow:Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x7f62931e6588>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Num'\n",
            "WARNING: Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x7f62931e6588>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Num'\n",
            "INFO:tensorflow:Done calling model_fn.\n",
            "INFO:tensorflow:Starting evaluation at 2021-02-08T20:34:01Z\n",
            "INFO:tensorflow:Graph was finalized.\n",
            "INFO:tensorflow:Restoring parameters from /tmp/tmpbi1_m7qq/model.ckpt-1200\n",
            "INFO:tensorflow:Running local_init_op.\n",
            "INFO:tensorflow:Done running local_init_op.\n",
            "INFO:tensorflow:Finished evaluation at 2021-02-08-20:34:02\n",
            "INFO:tensorflow:Saving dict for global step 1200: accuracy = 0.8095238, average_loss = 0.4403402, global_step = 1200, loss = 9.247144\n",
            "INFO:tensorflow:Saving 'checkpoint_path' summary for global step 1200: /tmp/tmpbi1_m7qq/model.ckpt-1200\n",
            "INFO:tensorflow:Calling model_fn.\n",
            "WARNING:tensorflow:Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x7f629111ef60>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Num'\n",
            "WARNING: Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x7f629111ef60>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Num'\n",
            "INFO:tensorflow:Done calling model_fn.\n",
            "INFO:tensorflow:Starting evaluation at 2021-02-08T20:34:02Z\n",
            "INFO:tensorflow:Graph was finalized.\n",
            "INFO:tensorflow:Restoring parameters from /tmp/tmplakvw6tp/model.ckpt-1200\n",
            "INFO:tensorflow:Running local_init_op.\n",
            "INFO:tensorflow:Done running local_init_op.\n",
            "INFO:tensorflow:Finished evaluation at 2021-02-08-20:34:03\n",
            "INFO:tensorflow:Saving dict for global step 1200: accuracy = 0.85714287, average_loss = 0.80776787, global_step = 1200, loss = 16.963125\n",
            "INFO:tensorflow:Saving 'checkpoint_path' summary for global step 1200: /tmp/tmplakvw6tp/model.ckpt-1200\n",
            "INFO:tensorflow:Calling model_fn.\n",
            "WARNING:tensorflow:Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x7f62930592b0>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Num'\n",
            "WARNING: Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x7f62930592b0>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Num'\n",
            "INFO:tensorflow:Done calling model_fn.\n",
            "INFO:tensorflow:Starting evaluation at 2021-02-08T20:34:03Z\n",
            "INFO:tensorflow:Graph was finalized.\n",
            "INFO:tensorflow:Restoring parameters from /tmp/tmpb439n4ub/model.ckpt-1200\n",
            "INFO:tensorflow:Running local_init_op.\n",
            "INFO:tensorflow:Done running local_init_op.\n",
            "INFO:tensorflow:Finished evaluation at 2021-02-08-20:34:03\n",
            "INFO:tensorflow:Saving dict for global step 1200: accuracy = 0.8095238, average_loss = 0.5919652, global_step = 1200, loss = 12.431269\n",
            "INFO:tensorflow:Saving 'checkpoint_path' summary for global step 1200: /tmp/tmpb439n4ub/model.ckpt-1200\n",
            "INFO:tensorflow:Calling model_fn.\n",
            "WARNING:tensorflow:Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x7f62910e94e0>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Num'\n",
            "WARNING: Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x7f62910e94e0>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Num'\n",
            "INFO:tensorflow:Done calling model_fn.\n",
            "INFO:tensorflow:Starting evaluation at 2021-02-08T20:34:04Z\n",
            "INFO:tensorflow:Graph was finalized.\n",
            "INFO:tensorflow:Restoring parameters from /tmp/tmp1rtyzyac/model.ckpt-1200\n",
            "INFO:tensorflow:Running local_init_op.\n",
            "INFO:tensorflow:Done running local_init_op.\n",
            "INFO:tensorflow:Finished evaluation at 2021-02-08-20:34:05\n",
            "INFO:tensorflow:Saving dict for global step 1200: accuracy = 0.8095238, average_loss = 0.41928092, global_step = 1200, loss = 8.804899\n",
            "INFO:tensorflow:Saving 'checkpoint_path' summary for global step 1200: /tmp/tmp1rtyzyac/model.ckpt-1200\n",
            "INFO:tensorflow:Calling model_fn.\n",
            "WARNING:tensorflow:Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x7f6290ebff60>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Num'\n",
            "WARNING: Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x7f6290ebff60>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Num'\n",
            "INFO:tensorflow:Done calling model_fn.\n",
            "INFO:tensorflow:Starting evaluation at 2021-02-08T20:34:05Z\n",
            "INFO:tensorflow:Graph was finalized.\n",
            "INFO:tensorflow:Restoring parameters from /tmp/tmpakeb8jrc/model.ckpt-1200\n",
            "INFO:tensorflow:Running local_init_op.\n",
            "INFO:tensorflow:Done running local_init_op.\n",
            "INFO:tensorflow:Finished evaluation at 2021-02-08-20:34:05\n",
            "INFO:tensorflow:Saving dict for global step 1200: accuracy = 0.8095238, average_loss = 0.8277211, global_step = 1200, loss = 17.382143\n",
            "INFO:tensorflow:Saving 'checkpoint_path' summary for global step 1200: /tmp/tmpakeb8jrc/model.ckpt-1200\n",
            "INFO:tensorflow:Calling model_fn.\n",
            "WARNING:tensorflow:Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x7f62933ca8d0>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Num'\n",
            "WARNING: Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x7f62933ca8d0>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Num'\n",
            "INFO:tensorflow:Done calling model_fn.\n",
            "INFO:tensorflow:Starting evaluation at 2021-02-08T20:34:06Z\n",
            "INFO:tensorflow:Graph was finalized.\n",
            "INFO:tensorflow:Restoring parameters from /tmp/tmpdz671cqr/model.ckpt-1200\n",
            "INFO:tensorflow:Running local_init_op.\n",
            "INFO:tensorflow:Done running local_init_op.\n",
            "INFO:tensorflow:Finished evaluation at 2021-02-08-20:34:06\n",
            "INFO:tensorflow:Saving dict for global step 1200: accuracy = 0.8095238, average_loss = 0.76806056, global_step = 1200, loss = 16.129272\n",
            "INFO:tensorflow:Saving 'checkpoint_path' summary for global step 1200: /tmp/tmpdz671cqr/model.ckpt-1200\n",
            "INFO:tensorflow:Calling model_fn.\n",
            "WARNING:tensorflow:Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x7f6291311d30>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Num'\n",
            "WARNING: Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x7f6291311d30>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Num'\n",
            "INFO:tensorflow:Done calling model_fn.\n",
            "INFO:tensorflow:Starting evaluation at 2021-02-08T20:34:07Z\n",
            "INFO:tensorflow:Graph was finalized.\n",
            "INFO:tensorflow:Restoring parameters from /tmp/tmpdc8v842a/model.ckpt-1200\n",
            "INFO:tensorflow:Running local_init_op.\n",
            "INFO:tensorflow:Done running local_init_op.\n",
            "INFO:tensorflow:Finished evaluation at 2021-02-08-20:34:07\n",
            "INFO:tensorflow:Saving dict for global step 1200: accuracy = 0.85714287, average_loss = 0.6239602, global_step = 1200, loss = 13.103165\n",
            "INFO:tensorflow:Saving 'checkpoint_path' summary for global step 1200: /tmp/tmpdc8v842a/model.ckpt-1200\n"
          ],
          "name": "stdout"
        },
        {
          "output_type": "display_data",
          "data": {
            "image/png": "iVBORw0KGgoAAAANSUhEUgAAAfwAAADZCAYAAADFRIIiAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAALEgAACxIB0t1+/AAAADh0RVh0U29mdHdhcmUAbWF0cGxvdGxpYiB2ZXJzaW9uMy4yLjIsIGh0dHA6Ly9tYXRwbG90bGliLm9yZy+WH4yJAAAgAElEQVR4nO2debxdVXn3v09uxktGSMgAJBFkCvMlIggqiljUOlZLNc5KKji19m0V41stNFqrotSKNQ4g5FpRrLXOWBzaOlCTwyiCAUIC5JKJEDKQ6Wa9fzxnvWffffc+Z5+zh3POPs/389mfc/a09lprr71/63nW2muJcw7DMAzDMMrNmHZHwDAMwzCM/DHBNwzDMIwewATfMAzDMHoAE3zDMAzD6AFM8A3DMAyjBzDBNwzDMIweYGy7I5AXM2fOdAsXLmx3NAzDMAyjMFavXr3FOTcral9pBX/hwoWsWrWq3dEwDMMwjMIQkXVx+8ylbxiGYRg9gAm+YRiGYfQAJvhpmTMHREYvc+a0O2aFMzgICxfCmDH6OzjY7hi1RlnSYRiGEaRwwReRy0RkrYjsEZHVIvLsBse/U0R+LyJPich9IvLGouKaiI0bm9teUgYHYelSWLcOnNPfpUu7TyzLkg7DMIwwUuTkOSJyMbASuAz4n+rvW4BFzrn1EcdfCnwCuAS4FTgL+CLwOufcd+tda/Hixa6QTnsi8ft6aGKihQtVHMMsWAAPPVR0bFqnLOkwDKM3EZHVzrnFkfsKFvxbgTudc5cEtq0BbnLOXR5x/K+AW51zfxnY9ingmc658+pdywS/WMaMiU6uCBw8WHx8WqUs6TAMozepJ/iFufRFZDxwJnBzaNfNwLNiTpsA7Altewo4S0TGZRtDIw3z5ze3vVMpSzoMwzDCFNmGPxPoA8KN2xuBuB5uPwbeKiLPEGUx8HZgXDW8EYjIUhFZJSKrNm/enGHUjUYsXw79/SO39ffr9m6iLOkwDMMI0+m99K8Evg/8CtgPfAf4anXfKAerc26Fc26xc27xrFmRAw1lz+zZzW0vKUuWwBVX1NYPOwxWrNDt3cSSJfCxj9XWDz20O9NhGIYRpkjB3wIMA2ElnA08FnWCc+4p59xbgX5gITAfeAjYAXSGCf/YY/z5Uoegy6rfOm0EfiwySaXmyCNr/9///u4VyWc+s/b/4ou7Nx2GYRhBChN859w+YDVwYWjXhagFX+/c/c65R5xzw8CfAd9zznVMF6pKBaZP1/9DQ+2NSzupVGD8eJg0qbvzwcd9+nRNk2EYRhko2qV/FfBmEXm7iJwoIlcD84B/ARCR60Xken+wiBwnIm8QkWNF5CwR+TpwMvDBguMdy/79cOedcNFFut7NQpeWSgVOOQWOOKK788HH/aKL4I474MCB9sbHMAwjCwoVfOfcjcBfAB8CbgfOA17snPNfPs+vLp4+4H3AHcBPgInAs5xzDxUV50bccw/s2wcvepGud7PQpcE5FfyBAZg7t7vzYWhIP8O76CLYswfuvbfdMTIMw0hP4bPlOeeuAa6J2Xd+aP33wBkFRKtlVq/W37PPhpkzu1vo0rBuHTz+uAr+9u1w++3tjlHrDA3B4YfDWWfp+urVcPLJ7Y2TYRhGWjq9l37HU6nA5Mnw9Kd3v2WbBt/WXRYLf+5cOO44/STP2vENwygDJvgpqVTgjDN0hLZuF7o0VCrQ16dt+HPnwo4dsHNnu2PVGl7w+/rg9NNN8A3DKAcm+CkYHlbX9cCArve64C9apD30587Vbd2aF17wQe/tbbfZsLqGYXQ/JvgpuO8+eOqpkYL/2GO9Jw7OaTt3MB+gOwV/eFgnOgwK/q5dsGZNe+NlGIaRFhP8FATbrUFF4sAB2Lq1fXFqB0NDsGlTOQR/82atsAUFH8ytbxhG92OCn4JKBSZOhBNO0PVuFro0RFV8oDvzwcfZp2HRIh1MyATfMIxuxwQ/BZUKnHYajK1+3NjNQpeGSkW/Wz/tNF0/9FAVyW7Mh7DgjxsHp55qgm8YRvdjgt8iBw9qZy5v1UJvC/5xx8GUKbouAnPmdGc+hAUf9B5XKtpXwTAMo1sxwW+RBx+EJ580wYfaCHtBuvWLBR/nOYEJmwcG4Ikn4KGH2hIlwzCMTDDBb4HBQTjnHP3/t3+r66CDtEyd2ljoBgdh4UL9dn/hwtr53cbgIBx1FDz8MPzwhyPTkVTwG+VFs3mV5Ph6xwwNwYwZ2jfDs2mT/h5zTPI4luUeNyLr+9ds+FmQxzU68f7nfa/yiFNW56SlNGXEOVfK5cwzz3R5sHKlc/39rjoHri79/brdOeeOP965V7+69fO7hUbpuPRS5w49NF0YzeZVkuMbHfPKVzq3aFG6OI4b59z48d1/jxuR9f1rNvwi0tApYaYl73uVR5yyOqcd8WxHmB5glYvRxbYLc15LXoK/YMHIm+SXBQt0//nnO3fuua2f3y00SscVV+j6nj2th9FsXiU5vtExZ5/t3AUXpI9jGe5xI7K+f82GX0QaOiXMtOR9r/KIU1bntCOe7QjTU0/wRfeXj8WLF7tVq1ZlHu6YMXprwohoR74lS+A3v4EHHmjt/G6hUTq+9CW45BJt916woLUwms2rJMc3OmbhQnj2s+GGG9LFMYpuu8eNyPr+NRt+FuRxjU58xvO+V3nEKatz0tJtZUREVjvnFkdeN13Qvcf8+fW3+7brOBFodH63kCQfoH47fqMwms2rJNvrHePcyGF108Sxmfh1K1nfv2bDz4I8rtGJz3je96oVWrlmt8SzHWEmIs70Dy/oXPSvBt4PTK9uOwY4NGkYRS55tuFPmDDSDRNse/nkJ3Xbtm3x53da+14rrFzp3KRJ8elYvVq3/du/1Q9j3Lj4MFaudG7ixOR5lbQNP+6aW7fq+lVXJQ+z19vw+/rq502afOjmNvx674h2UKY2/KKfrTyu2ejZSQNp2/CBpwNrgS3AAeDo6vZPAl9KEkbRS16C75xzr3iF5pyItrkEb9LgoO67557481eudO6QQ/S4mTO7VwiWLYvPhw0bdN/nPlc/jIGBWoE/8sjRefGWt9T2h68RxVe/Wjt+/Pjo408/Pfqad9+t2/71X0cev3Klc0cdpfumTRsd5nXXjY5j8B7Pn9+997gRhx5a//4873m1/XPnNp8PwUrfjBn55OPy5bU4Tp6czTVe/ermym0RBCvpU6aMjtPKlc6NGaP7x44tJs433KDvD19RTnLNl72s+Lz94z+uXXP27GyuecQRej+i3p9pyELwvwesAPqAHQHBfw7wQJIwil7yFPyXvMS5k0+O3vfTn2qu3nJL/TBe+EI97oYbso9fUXzqU5qGjRtH7ztwQF8eH/pQ/TCOOqompj/84ej9l1xSE4sk3HmnHn/UUSr4+/aNPmbevNo1b765tv0nP9FtP/95dNgnnqgvmzCVip53440jt19zjW5fvz5Z3LuNzZtreQ3ODQ2NPmbx4tr+665r7Tqnnabnf/CD6eIbx5e/XEvHM5+ZTZivepWGuXhxNuFlha+APec5o/etXVvLBxHnnnwy//isWVO75pgxzu3a1ficiy7Sc444Iv/4eV7wglo5/sxn0oe3a5em98MfTh9WmHqCn7QN/1nAJ51zw6Ht64F5TbcjdDlRA814kg6+4/fv3p1dvIqmUoEjj4TDDx+9r69Pt9fLh82b9Rv+t7xF11evjr4GJM8nf/zb3gb79sE994zc/9hjsGEDvPWtI4+H6FH2ggwM1I9juEyUfeKd227T37e9beS6Z98+uPNO+NM/hUMOaT0f/H3JayCnSkXHz/iTP4E77tAJsLIIE2DPnvRhZYl/jqKmfPZl+21vU1v2jjvyj0/weT14UMtLPZyrxXPbtnzjFrxmpQIXXQTz5mXzPN95p6Y3TkfyoplOe+Mits0HtmcUl65gaEgXE/yRU+JG0WjwHS8Q558Pxx47+kHatw/uukv/NyP4kyfDxRfX1sP7AS64AJ72tOYF/9FHdfrccJhTp8LRR4/cfuqpWvGJqiSUAZ8uX2EL5/U99+g9fMYz4PTTW3tRHjigFUPIV/DPOAMWL1aB/v3v04W3dWttVMZOFfwdO+D++0fuq1R0XpA3vrG2njerV+t8FW94Q229Ho8+quVhzhxNy759+cdx3Tp4/HF9/uMq/c0SZyTkTVLBvxl4X2DdichU4O+A72ceqw6m0Y2aOhUmTar/ctq3D7Zs0f/dKvg7d8J996UTfJ+XZ5xRG68+iBeMk06C/ft1aUSlouJy3HEq/HGCf/rpo685NKSWqJ8TIIxPa9iS9YIxJvQ0TZoEJ55YXgu/UtFKzvz50RW24LMyMBBtVTZi40a1sCAfwR8ehttvr8UR0t8vXz4WLICnnkoXVtbs3q3PE0Tfr5NO0orwnDnFlNtKBU45Ra85a1bja/r9z3++/j7xRL7xC17Tl5Hf/z79e7tS0fQecUT6+DVDUsH/K+A8EbkP7a1/I/AQMAf4QD5R60yCghGFSGOhC1qI3Sr4d9yhL+K0gn/00TB9uobz0ENakw7uBzjvPP1t9PIcHq5NaDRmjIpw1EvNT/QzMKBWzvaqjyr8SV4Yf8+DYR44oHkRlw9RFZmyEGzaikpnpaL5fMwxun/XLvjDH5q7hi8/s2fnI/j33qvlamBAy0V/f/r75c8/55zOtPAXLx495bN3lde7n1njXeUDA/reTHLNSkWf7fPP1/Ui3PqVinrqTjlF45ik6aERPq9FsoljUhIJvnPuUeB04OPAF4BVwN8AA865zflFr/MIzwwXRSOhC+7rVsFP4pKaO1fHoR8O9/wIhBF8wcBI69kLximn6HqjvFqzRkUlGObtt4+8ftQ1b79dfxsJ/vTpKl7Bl9J999UEI4qBgVozUJl44gkdXCqYl1EVNu/5aNV69vk2MKCu3Cza14MEy3FfX+tND+EwFy5U660TLfzp0/WZCqZzwwbN3+D9vOeefOO/fn3NVe6veffdsHdv/DmVCpxwQs0yLkrwFy1Sj10WXqC9ezWdRbvzIYHgi8g4EXkM7Zn/Fefcu5xzlznnvuSc67DinD/1Oux5ekXwDz9cO7HEMXeu1ob95DNBwoJxxhm1cIPXOOMMdc1D47wKV0IGBvQcb1Vu3artcXHXbCT4PsxwHIPXjDoeRjcDdDu+khRXYQu6ykGbNiZMSCf4zo3uP5GWSkVf5McfX7tOK00P4TAHBnQCpj17ak0SncDu3erFCE/5HPXsDA/X+tDkQdQ1DxxQMax3zsCATnAF+bv0w56PI4+EmTPTCf7dd2s6O1LwnXP7gf1ABxXb9rBli9ZKsxL8CRO6W/AbuaTqdWAMC8Zhh2mbp3+QgoLR36/bkgj+xIkqLsGwfZhejPz22bPVUvCdcDZsSCb4a9fWLIuwYISJagYoA8H+F8Ffvz3s+Rg3Tjsxtir4Ph+z9pRUKnDaaWrdQ63pYc2a1sJ78kk91wv+wYPZeyVaxfeD8YK/bZtWgEHzQUTzAor5wsS7yk89Ndk1N27UTntBwc/bwh8aUoPFxy1p00M92tVhD5K34X8WuFxExuYZmU4nLBhxzJ2rD36cQA0NacFZsKA7BX/PHvjd75LlA6iQhgkLBox8kIKC0Yzgn3qq9jQGdf1NnFgLs941d+zQF30SwYdaWfCdBL1ghJkyRZuAyij4wU8ywxW2qJda2KpMwtCQWlR+yNEsBf/gwVqfj2AcofX7FazITpqk/zvFre/j4QUfRt6vE07QTqug+X3oofkL/okn1vLpaU+DadPirxl8/06frv/zFvy4ctyo6aFRmNOmaXqLJqngPxt4OfCoiNwiIv8RXHKMX0cRJRhRNPo0b2hIe2hOm9adgn/XXWqBJxX8qHwICwZoeH/4g1aWgg9aEsEPdgDyjB2rFkvwpbZwob7Igte8997aJ0qNBD9oyUYJRhRl7LgX1bQVTGeU52NgQDtIrl2b/Dq+mSXp567N8MADWtELpmPRotEd2pohWG4nTtT/ndJxzz8//f3aht/XN/J+BfMhC0u2Ec1eM9hhuiiXftjzARrH/fvV6Gk1zHZ02IPkgr8F+BbwA3Swna2hpSeIEowokgj+3Ln64HWj4Cd1Sc2Zo79xgh8lGKC93oOCkUTw165VMYkToYMH46/pHPzoR7reSPBnzYKjjtKwogQjioEBdZ1uLcmTsmuXVpKi8jJYYTvttJq3xe+H5kTEPyuzZ9fWsyKqHLfa9BAMc948jW8nC/6kSVq5qVTUZf3II9H386678vnWfWhIB8GKuuYdd0R/glupwNOfrobShAmahiIs/HAn7TReoP3763/VkzdJe+m/pd6SdyQ7hUoFzjyz8XG9IPjTp2vlpx4TJmjlKJwP9QTDhx8UjCSCH1cJGRhQAbrjjlrbatQ1v18dTaKR4PtzfByjrhl1PJSn417cJ5nBdEZ5Pk4+We9nK4I/fry69rMW/HHjat+le1ppegiG6dPdaS79oOCDxnP16vrPzr59rVuy9ah3zb179f0QdU7w+OnTixH8cByPPrp+00M97r1X09fRgu8RkaNF5I9F5CUicnTjM8rD9u3q9k1yo3pB8JO6pKI6MMYJxpw5evyqVSMFI6ngjx2rohLEh/GVr4xc9xxxhFrtv/51Lb6N8JbsL36hQrRoUf3jo75A6GbqvawBbrpJK1nh/RMn6v1Jmg8HD6oV6O9Jo86wzVKpqGt7/PiR2wcG1FXsR8tLyu7dOiiLT3cnW/ig8dy0qVbZDY8tkmfHvaB7Psk1t21TL16wTM2Yka/g+6G/w+VYJHqMjyS0s8MeJBR8EZkqIt8E7gf+HfgOsEZEviEidb5ILw/hXuX1OOwwFZ+ol9PwsPY27VbB379fB51IWmCjXtL1Cv3AAHzveyMFI6ngn3yyehWCnHSSWnErV0Zf07cbHjyoL/5GzTU+DOfgX/81WjDCHHqoekPKJPhRn2T6CltcXvttSa3nrVu1h3segh/V5yMYR2j+foXHR+8GwQe9X8ccU+sI5znmGHVl5yX4UeOZHHts9LwLUR2mZ8zItw2/Xidt3/TQ7BcYlYqm79hj08evJeJm1QkuwLXAfcBz0TH1xwHnA/cCX04SRtFLlrPlrVypU3PGTeEadbyf6zg87eFjj+n2z37WuT//c51qMS6MBQtqUydeemm69ag4t3KNuXNd4ml9g1PEJp021k89HJxO9YkndP1Tn4q+xvz5uv+QQ6LjtGBBLcyovGh2us3PfrZ2fNLpVBcv1ilHs7p/4Xvn87aZc5q9hj8edMraRlMPR93fN73JxU6pHOaOO/TYb3yjdu6RR8Yfn5SVK3WmNdDpfcNxuPbakeUhKp+i8sa/I444Qvf7mTN/9rNkcUr7/DYqh9//vsbn1lt13c8SWG8u9uOP11knmymHSdJV75rHHuvchAkjz5k+ffT79yUvce6MM+qnuV4cGt3PqGt6Lr10ZDlO+jyDpi3PKX3JYHrcrcCzI7Y/B9iaJIyil6wEf+VKLZj+wahXUJMcf9ttuu2mm5z7y7/UeamThJF2Ccc5i2s0mw/jxunLIy6MlSv1YQjv93PcX3ll8/cmWPmKu2a9OKUtD/6cceOyy+tW87bR/U5zfFw6k9zfuLz70Y/0mP/+b13/wAe00jQ8HJ/XjWh0/5KkOyqvo/Lmwx/W/1HTPjeKUyvPb6Ny+M1v6nF33ZX82Rk7trm8yqIMha8Zd87rX+/cwoXp8zbp/Qyma+LE7J7nrMlC8HcDiyK2nwzsShJG0UtWgh+0DoPLggWtHf+DH+j6L3/p3LJlKkYHDyYLI+0SjHNW12g2H+qFUS/vxo517vLLm783jY7J+v6mzYs0+ZTFOa0en0dee0v7/vt1/eqrdX3Tpvi8bkSrcWxl8d6wb3+7tTilyesofMX5gQeKeXayTFfUOe9+t1rhWeRtHs9GM+nOkiwE/yfoZ3n9gW2HVLf9JEkYRS9ZCb5I9M0Sae1470Z78EHnli/X/3v3Jgsj7RKMc1bXaDYf6oVRL++mTnXuve9t/t40Oibr+5s2L9LkUxbntHp8Hnn90Y/q/l27dP0b39D1O+6Iz+tGtBrHVu8XOPe1r7UWpzR5HcXnP6/HDA0V8+xkma6oc/7v/9Xfeh6frO9nlmHWu1dpqCf4SXvp/yVwNjrwzi9E5BfAw8Azgb9ops+AiFwmImtFZI+IrBaRZzc4/nUicruI7BaRx0RkpYjMaeaaafAjfGW1PTjnelxntLgw0hIMN6trNJsP9Y6tF1ZUB8ck1250TNb3t9l9zdAozlmc0+rx9c5pNa+HhnS6af+cZDH4TqtxbAXfqbFRp7088jqKYKe9Ip6dLNMVdc6MGSqdfrbLRmGnJesyktd7vi5xNYHwAvQDlwCfqi5vByYlPb8axsXouPyXACeiQ/buBObHHH8uMIxWOJ6GVjoqwC2NrtWpbfjvfGfNDfWFL+j+Rx8dHcakSdnVTKPiHNWemjbMRvnQSjuz33/00c4tWdL8vWmlnTGPNvws+0u0mrfNtlNm3a7cbN69+tXaacxz//16zrXXxud1I4psw//c5/T/Ndc0H6ckeR1uR25UDq+8Uo/bt6+YZyerMhR3jm/yefDBdHnbSht+nv2f0kJal35WC3Ar8MXQtjXAx2KO/z/AutC2twA7G10r6176zfSGXbnSuaOO0tydOnXk8a96lXMnnqj/b7hBj1mzZnQY//APui9NL/2ZMzUM39s9zF/9VbprJMmHtD3J/f6TT3bula+Mvkb4S4Ak8Whmf7PhJTknSV5Pm6bpiurtvnKllq3g/uCLKCpeL3rR6Ps9e7ZumzVr9PGf/nTtBZVVz/Ek98tz7rnOnX9+bX3XLj3vox+NPycJ118/Ml2NykPSXt3hY+p9XRImeD99eP7rk/A7xPO+99XS4b8MqMfll6u4xaUz7n56F3bUMd5oqZeX3rBotQzFnfPtb2u4q1fXT3c4jq3ez2bimPbdmYbUgg8sB94Rsf0dwJUJwxgPHABeE9r+OeAXMeecA+wDXgoIMBP4MfCNRtfLUvBb5dRT9SUb5JxznHv+8/X/t76ldyCqTfLXv9Z9jXr41uM739EwVq2K3n/jjbr/7rtbv0ZRnHWWc3/0R9H7XvEK5045pdj4FMHHP673Z+fO6P3vec/oTkv+nK1bRx9//vnOPfOZI7ft2KEvoSuuGH28L5+//W1r8Y/jve+N/jolzNFHO/fa147cNnWqdtZKQ/DT2DzZs0evs3x5suMvu8y5ww4buW3ePOfe+tbo44NC9t3vNg7/ve/VSmSzzJ0bHwfvdTn55PjzzzrLuYsuav66jfj5z/Xa//mf9Y+75RY97uabs49DJ1JP8JO24b8BiBoYdDXwxoRhzAT6gPCM1huByDZ559yvgT8DBlHh34wK/5uijheRpSKySkRWbd68OWG08sMPXal1FyU453q9AWV27NDf8MAUzdBowJrwQBydTL1BinbsSJdPnYpPky8LYaLSHTdoTNxcApMn63wFforgIKtXR49emJYZMzTu9QYtcW7ks+KZNy/94DvBfjR5Mn68DuyUdOAdP1d9kHqDDfntIskGx4kKPwn1Brjx2+PKqN+Xx/OZdAKddo9u10kkFfzDUbENsxWYnV10RiIii9B2/iuBM4GL0MrBF6KOd86tcM4tds4tnjVrVl7RSowfutI/mOGXWD1B3rlTfydPbv36vSL4O3emy6dOxafJl4UwUemOE/y1a6OHu/XnRAlGpaIjFfoR47LCv6jrdbZ68kkdgz4sylmMtleU4Ito3iUdS78VwZ85UytseQt+3BC2fntcGfX78ng+k06RW6no1M2HHZZ9HLqNpIK/Hp0iN8xzgEcShrEF7YAXriDMBh6LOedy4H+dc59wzt3pnPsxcBnwBhE5MuF120b45fvEEzpxgu+9axZ+cszCH01UuuOG8W00nPHDD+vY4R7n1MLPwypK8qKOE+VuEnxQwc/Twp87N/k0tnkKfjst/CSCb9a9klTwvwB8WkQuEZFjqstStLf+iiQBOOf2oU0AF4Z2XQj8Kua0frSSEMSvNzXxTzs47bSR7rbwi6ZTLHw/q1cnYxb+aHbsiE53lADEzQznj4eRs/lt2KAVgDxelElcsY0EP9hM1izdJvibNkU3fwQFP1xhSxp+EqZPb+zS37cvehpd5+LLaVomT4a+vvrlaMcOnejKBF9JOj3up1DR/yfgD9XlarTH/T82cb2rgDeLyNtF5EQRuRqYB/wLgIhcLyLXB47/LvByEbm0OlPfudU4VJxz65u4blvw7aOtCH5RFv748SPnLO9UzMIfzc6d0ekeGNCpgJ98srYtbnIhiJ7NL892zySWWT3Bf+qpkWlrlqEhFbGsmyqimDQpvUvfORX9MEHBh8ZWfp4WPkRXTPfu1QnD8ng+RRpPkXv77Zp/JvhKYivZOXc52vHu7Ooyyzn3gWYu5py7ER2o50PA7cB5wIudc+uqh8yvLv7464D3Ae8C7gZuQisbL2/muu0kaG01a+GPGZPupZRE8LvBnQ9m4UdRz8KH2gyPztV3a06frnN8hwVfRL1UWZPWpR/c3wpRnQHzIgsLH0anNzh1cNLpl9MI/vbtKtxhGgm+r6zm9Xw2miLXOuyNpCm3uHNul3Put6j4ni0iC5q9oHPuGufcQufcBOfcmc65/wrsO985d37o+M86505yzvU75+Y655Y455L2G2g7QXdbsxb+lCnJ5pyPo4yCH3bl7t2rU/aahV8jbPE98ghs2VL/pRduBqhU4IQTdCrPrEnq0p84EaZNG7ndBF8JTh0cVWFLGn4SfAUtyqsSvIdR5dRXAvJ6PhtNkVupaB7NKWxs1s4mkeCLyHUicln1/3h0AJ2bgftE5EU5xq/rCbaPDg3pC9QXft92Hmfhp60VT5igFYayCL5zKvBBsujr0Km0auHPnq0dQ70AJLFyBgbggQdqL888OzoldenPnTu6wtttgp+FSx9GpzdsPJx5Zr4WPkTfr3Zb+I1c+tZhbyRJLfw/An5T/f8yYBr6edxHqosRQ9DdFn7R9PWpKNez8NMgUt8V3m2CD6PTkkVfh07FvySjLKfhYRWSuHQHLfZKRZuHTj01/lrBZoBNm9QrkNeLctIk7TvSSPD91yxB0gp+3LYnK6IAACAASURBVPf9eZHWwp9d/aapkeAPDMCDD9bP07wFv10Wflyad++Ge+4xwQ+SVPBnAL7byEXATc65TcDXgUV5RKwseHfb6tXRL5o4Qc6qZ2uvCH4ZLfzx43WJspwaeTYGBuD3v9f8qlTgxBPr3+tgxdT31s/rRek7WzVy6UeJ8tSpWmFoVfD9p7FFWvhpBH/8eP3WPongQ63fRtLwk+Bd+lH3a9u2WqWkXW34ceXorru0r4MJfo2kgv8YcLKI9KHW/n9Wt09GJ8Mx6uCtrWYEP659tlnKLvh5WxDtZsqU1iyngQF92d15ZzK35uGHw5FH6rHeM3D66a3HuxGNOlvFCb5Ium/xi/wkD5IPvHPggH7WFvU8RqU3nI5GHfecy8fCf+IJOOoo/d8OC9+79KM+07QOe6NJKvhfAW5EO+sNA7dUtz8TuDeHeJWKM89Ud9u6dWbht0ovWvig6WrFcvIvuR/8QL+pT/LS8xXTSgWOOaZm2eVBI1fs9u3xotxtgp/EwveVgmYEPzh18KxZKrxxgr93r4piHi59L/jtsvD3749+x1UqOrqej5+R/Dv8K4C3ooPsnFcdRAd0MpyP5xS30uBftlGuRLPwk2EW/kgapfvII9UVfO21un7mmY2vdeaZcO+98MtfJjs+DfU6WzUS5W4S/KQu/XqjXsYJfjgN9UbcSzOqZpxL3zm9h35e93a14UfFDWqerTRfOpWNZr7D/5Zz7tPBT+Kcc191zn0nn6iVB+9uA7PwW8Us/JE0SreIvuweqT6tSdzzAwO1Tm15u0Hrtb2WSfCTuvSTCP7Bg7VtGzZEC/5990WXlzSC70e0C1fQdu3SzqPz5ml5a1cvfRgdt337tA3f3Pkj6fjhacvAzTfrAwPw138Ng4O1fWbhJ8Ms/JEkSXdwVL1TThlZ7qJ46KHa/6uuanx8GuJc+oOD8MpX6v+3vGV0HAYH4YYb1OU/f76uDw7q/AFjxuhvvXgPDWlZKqq8JHXpNxL8Awf023tPlIX/5JNaYZs6dXQ+pBF8kej75dcPPVQFPa6cjh0bPcJjFkQ1N/jysH8/fPnL+ZbjbqMLBlXtbgYHYenS2ihVmzbpOsCSJfoAPv74yHMOHtTac1YW/qOPRu8rg+D3goW/YcPo7Y3SPTgIP/5xbX3dupHlLur497+/th4up1nje+k7V3O5+mfF3+OhoZFxCO9/+GGtFIjUxnFvlM647/vzwrv0g+mMopHgg8Z91qzoTwsHB+Gaa/S/c6PzIe1EWVEeGS+y06fHV0y9pzKv/A679MNlZMuWfMtxt2EWfs4sWzZapHbv1u0QbYHv2qW/eVr4Bw+qq7HbBd8PQdwNEwC1wpQp9T/Liysjy5aNnswkWO6ijq9XTrNmxgytBAfT1igOUfv3728unUV+gw+1obHDA0aFSSr4oN6NPXtGpmPZstFNB8F8SCv4UX0uvMjOmBHf9JSVp7JevKAWt6LLcbdhgp8z62Om+PHbowQ5S6s1TvC9m7HbBT9vC6LdxLlKG5WRRuUu7fa0RLliG8WhmbjEHbthQ/SAPnnhBb+RW78ZwY/qh9Ao77Kw8ONc+jNmNLbw8yJcjooux91G0qF1PyMiJ+cdmTIyf3797VGCnGW7dJzgp30BFE09C7+s7ffQ2MKPG+u+UblLuz0tUZ2tGsWhmbjEHVu0he89T3kLfqO8y9ul3y4L38+14ONWdDnuNpJa+M8A7hCR/xWRpSJS4ldstixfPvoh6+/X7f5/Oyz8bhP8uHkH8rYg2s2UKdFzje/YoffOdwYN06jcpT0+LVGfUzWKQ9T+ceN0NLq4c4Ls3KlLO1z6jXrq13se+/u1I149wW+Ud3m79Ntl4Y8dq9f2cVu+fPQMo3mW424j6Xf456JD6P4M+DAwVJ27/rl5Rq4MLFkCK1bAggXqdl6wQNd9B5L+fn0ZBD+5ydrCP3BA2zqDdJvg+6mCe83Cj5tAp1G6G5W7tMenJcql7+MwpvpWCschKo7XXgtf+UqtF3i9eBf9SR5k49KHkZ8iRqXD5433+ITzISuXfnBEu23b9D5Mm9Y+Cz8YN9D0vulN+r+IctxtJO6l75y7D3i/iFwOvBgdiOdmEVkPfBlY4Zx7vF4YvcqSJfEFzj+Ae/bU/mdt4YM+8MGpRrtN8CHeG1J2Cx80nYceWtueJN31yl0Wx6ch7vvp17wGXv96+MhH4MMfHn1eXBy//3249Vad8S+Odgi+90ylsfBhtOBHTR28ZInOg/D5z4/8xDJJ+I2YMUMNh927a5WKbdvU8zBmTPssfB+3oKdo4kTN9x074j1gvUornfbGAVPRGfP6gPXAG4D1IvK6DOPWE0S1TWdt4YfDD653u+Cbhd+dxI2QtnGj/jYryl4Qo8ZU95TJwo/7tHDGDA0r6suFeuE3IqqCtm1b7T6208IPNzdUKjrQlIn9aBILvogsFpFrgCHgH9Hpco91zl3gnDsJ+Gvg0/lEs7xECXJeFn6Qsgh+L1n4Qbo93VOnqmCFLfxWRXnuXLWin3wy/phOF/y+Pu2TEEWwQlOv42Gc58Q/N+H27aRENcE88URtu+9cGmyahOIsfB+vgwfVy2Ej7EWTtJf+XcCvgKOANwMLnHPLnHNrA4d9E5iVeQxLjln4yTELv8aOHd2d7jFj1CWdpeAHz49iaEg7+AWbRvKmGZd+f3/856XBCk09wY/znOzerXEZ0+KH2FHhbttWq2D4chp8Pg8c0DgX0Ybv43X//fqs5D0XRLeS9PZ/A3iac+6lzrn/cM4Nhw9wzm1xztl3/U1Sz8KP++QqbfjB9W4X/G63dBsRZ+Hv3Nn96Y761CtvwZ8zp9gxG5qx8Os9i8H0JRH8KAs/zbMeFW7QpR9VTv0AYkVa+DYlbn2Sdtr7OBGVAxGZCBwMzJ5nNEmchT9pkn5ykkf4wfVuE3z/EgEdqW337u62dBtRVgsfogdzGRpSQZ49u7mwkgp+ke58yF7wH3hArfyiBT+qqSDo0o8qp178i2jD37VLv0SqVNSLs2hRvtfsVpJa5N8ELovY/g7U+jdaxD+EQSHL0motm+AH01GUBdFOymzhR33b7ceLb7ay26mC36xLPw4f79tuG7keJm4q26ws/DiXflQ59eJfhIXv41apwKmnxveF6HWSCv65wM0R238CPCu76PQecRZ+VrXiMgt+2WfKg2jLyblyW/itiPK0aWpNd5rgZ23he5d10Ra+/wTQh7t3r1Ziwi79dlj4wTRXKubOr0dSwe8HDkRsPwh0+WunvcS14Rdl4bfaa7cdhAW/qBdKO/EduYKW05492hu52y38uDb8VkRZZOSna2H27tVZKbtV8H2FppHg1+uln0bw+/r0ywofbnCUPaiVxXZY+D7Nt92m8TPBjyep4N8JvDZi++uAu7OLTu/RTgu/Xq/gTiTOwu924auHyOhvnMtS0Ylz6bcqyvUE/7HHascUSVYufV+hWbdO1+PSMWGCXjNrwYeRFbTgOPrQGRb+Lbforwl+PElbyq4AviMiTwd+Wt12AfAa4JV5RKxXiLPwfSHOI3y/3k3ufOhNCx9Gj2JWlorOjBlq+e7Zo9br8LAOvJNG8H/3u+h97fgGH7QvQl9fegsfNO5r12qYM2fGHxflOdm9Gw4/PFmc64XrhT44Ux6018IPCn5fH5xySr7X62aSjqX/A+ClwALgn6rLfOBlzrnv5Re98tNOCz+Lz/6KpL9fXbPD1Y9CyyJ8jSirhR/uCLZli97bPCz8dgk+aGUmieA3eh593GfPrv89fVTfiCwq+EGPTFjw22nhey/Dgw/CSSd1VzNl0TQzlv6PgB/lGJeeZMIEddfl1YY/dqx+plIWCx/UPRqcJ77bha8RZbbwQcVjzpz0ojx3LmzfruXDu9I97RT8SZPSu/ShFvdGaYhqKsnKpb9mjf73lbTwwDvttPDB3PmNsIFy2oxIdNt0liIWNWBNNwq+t4B8WsoifI0oq4Uf7mCWheAHwwkyNKRWcVq3disktfCzEvw4l34Wgh9n4Y8dq+mMKqd5exInTqxZ9TbCXn2SDq07XkT+TkT+ICJ7RGQ4uOQdybITFGT/yVWWIlYWwQ83T5RF+BpRdgvfi1Negj84CJ/+tH7ZcMwxul4kjQTfuWTPo58B77vfhYUL49PRDpc+jPS6gZbT/v78J7EZHKxNFvT3f1/8/e0mklr4VwJvAj6Ffor318DngK1ED8hjNEFQkPft0zGozcIfTVjwvfB1W1+EZimrhR/+ZjwPwR8chKVLa4M0rVun60WKQiOX/r59Whmp9zwODsL119fW66Uj7NIfHta+L1lY+H4mviee0PDGj6/t9xPoeIoYK8LfXz9pz8aNxd/fbiKp4P8p8A7n3BeAYeA7zrn3AB8GLswrcr1CUJCznCkvKnxPGQR/x47shiDuZMpq4Ue59KdPb73TVZTgL1sWXfaXLWvtGq3QyMJPMgjWsmUq2uHzotIxY4YOv+tF0Fc2shB8ULEPjrLnibLw8y6jnXB/u4mkgj8buKf6fyfgb/WPgBdmHaleIyjIeYweV1bBL8Pwskkou4UfdOmn6VQ3c6ZW/oKCv3599LFx2/MgC8FvJh0zZmgzwfbtycNPQtAjE5w4x9MOC78T7m83kVTw1wPzqv/vB/6o+v8coEH/U6MRZuEnI8rC73bRS0J4rvGdO2tfX3Qz48Zpc0zQwk8j+GPG6CdrQcGfPz/62LjtedDIpZ9EkJtJR9hzkpXgB8MNTpzjaYeF3wn3t5tIKvjfRgfaAbga+DsRWQtcB3ypmQuKyGUisrba+W+1iDy7zrHXiYiLWHbFndONmIWfjF628GF0RaebRkmMI9jenMVY9/PmwYYNtfXly0dXjPr7dXtRZGHhL18+en9cOsKek6wt/DiXfjss/GbyxUg+8M7lzrnl1f83AecBnwVe5ZxL3FoiIhejFYaPAmcAvwJ+KCJx9bH3AnNDy4OUbIY+s/CT0csWPtTKRpkqOr5HuXPZCH548J0lS+D5z9fKkQgsWAArVuj2oshC8Jcs0XgvWNA4HeHOkEW59Nth4TeTL0aCgXdEZBywEvigc+4BAOfcrcCtLVzvfcB1zrkvVtffLSIXAZcCl4cPds5tB7YH4nIucDTwhhau3bEUbeHv369Ltwv+zp3ZDUHcyYRHMStTRcd/M75tm3ZKy0Lwf/Wrkdt27YKzzx69vSiycOmDilgSIWuXS78dFj4kzxcjgYXvnNuPdsxzaS4kIuOBMxk9ze7NJJ9i9xLgd865Nj26+RBl4ecp+Fn12i2aXrXww6OYZT0wUzvxLv2sRsKbO1eH6PXfZR88qLOotXMEtiws/GbI28LfulU7BCbppV+WcloWkrbh/xvwqpTXmgn0ARtD2zcCcxqdLCLT0M8Dv1jnmKUiskpEVm3evDlNXAslysLP06Wf9QumKHq1DT/Kwi9Lur1L3wv+vHn1j2+ErzBsrL5l7r9f862dgj9pUnsEP+s2fD8Tn5+xL8rC379fK1t5DCBmpCfpF8zrgQ9VO9itAkZ0mnPOXZV1xCJ4PVpBuSHuAOfcCmAFwOLFi1N5JIqkKAvfuZHj9neb4I8bp6N2mYXfniFi88C79LO08EHDO+qo2vzx7bbws3DpJ+WQQ/Q5ydrCB7XqH3xQ/0e14YOW0/5+9a70wvPZTSQV/DcD24BTq0sQByQR/C3ooD2zQ9tnA48lOP8S4FvOuccTHNtV9Pfr6Hr79+vLvK9Pa9NZhg9qZUya1L2CH5x3wDmz8MvA9Ok6SMwjj+h6loIPKvjjx8OiRenCTcPEifpsDw9HDzOb9fMoMnJ43SzDnzFDp+iF6F76oOXUz2hZlnJaFhIJvnPuaWkv5JzbJyKr0ZH5vhnYdSHwrXrnishZwGnAX6SNRycSdFXn8clVMPxuFnyoCf7evdkPQdyphC38Mnk2vJV4771qmaZNV5Tgn3JKe8cs8DP3xQ1v64f9zfJ5DE6gk7Xg33df7X+QYDk9cED/l6WcloWiZ8u7CniziLxdRE4UkavRAX3+BUBErheR6yPOWwqscc79vLioFkdY8LOuFYfbvssg+Hl8vtiphC38Mnk2vGjcc082U9fOnq2V5aEh9QJVKu2fMtUPFRzn1vfPY3hK3zQExzfIWvC99R7Vhg9aPssy/HPZSGThi8g/1dtfHVe/Ic65G0XkMOBD6Df1dwMvds5Vu4Ew6nt8EZkC/BlwRZJrdCNBQc6jZ2sZBT+Pzxc7lbDltGdPedLt3cL33gtnnJE+vLFjYdYsFfx161T0OkXw4zru7d6tx4zJ0PwKu/T7+rQPTFqCbvyoXvpgFn4nk7QN/5TQ+jjgBLTX/W3NXNA5dw1wTcy+8yO27QBKXU80Cz85vWjhB+caL5vl5K3EnTuzsfChNvhOJ3TYg5rlXk/ws34WZ8yoTafrw8+imTBo1dez8K0NvzNJ2ob/vPA2EZkIfBn476wj1WuYhZ+cXrTwofaNc1kmzvEERSMPwe/rg1PD3YwLJolLPw/BD1r4WX/yN3bs6GmpzcLvfFp2Ijnn9qBD5NpEhCkxCz85vWjhQ20Us7JZ+EG3cB6Cf9JJrU+3mxVJXPpZP4u+Dd+5bMP392v69NEeA2vD73zSthrNpOTu9iIwCz85ZuHrelnSnZeFv3EjrFrVfnc+tM+lf+CAhp2HhR81pHXQwi9bOS0LSTvtvS+8Ce10twT4QdaR6jXaZeFn2Su4KMzC1/WypLu/XzuT7d+freAPD8PmzZ0h+O1y6YNa+UUJ/qRJ2vHQ2vA7l6Sd9t4dWj8IbAauBT6WaYx6kHZY+OPGZdNrt2h62cLfvr18lpOIuoc3b85W8D2dJPj1LPxwe3haghPd5OXSDyNS80QdOKDvlywHEDPSk3R63KeFlmOcc2c75z5Y7UVvpMA/jDt26MNZhIXfje58MAu/bBb+4GCtc9mLXqTrabnrrtr/1742mzDT0C6XPmQv+H7GwZtvhoULR+dtsJyWpYyWiaQu/fHAmGpHveD2icBB59y+PCLXK/iH0c/3U4SFXwbB7+trf4esoihjG/7gICxdWuvR/cgjug6tT3c6OAj/+I+19YcfTh9mWtrp0n/iiezCHxyEK6+sra9bNzpvp0ypWfhlKKNlI2mnvW8Cl0Vsfwfwjeyi05t4C8DP8JV1zdi/cMoi+MPD8Pjjmk9ZDkHcyZTRwl+2bOQsjqDry1J897Ns2WhhTRtmWtrVSx+ytfCT5O3kyWbhdzJJBf9cRs9jD/ATks9lb8Tg29M3bdL1rGvGwUlnoPsFHzSvesmCCFv4Wbf5toP165vb3q4w0+Ir9N3eaS9J3noLv0zzPZSJpILfDxyI2H4QsNuaAf39+Vn4PvwyCf7Gjb1lQfi5xh9/XMU+y2FY28X8UQNp19/erjDT0g4Lf9o0/c3SpZ8kb83C72ySvjbuBF4bsf116Hj4Rkr6+/Oz8H34ZRL8XrTwQQeUKUu6ly8fXQ77+3V7J4WZlnqCPzwcP4teGvr6YOrUbC38JHlrFn5nk/SzvCuA74jI04GfVrddALwGeGUeEes1irbw58zJ/hpFELTwjzqqvXEpEv/yHBoqj+XkO3otW6Zu4fnzVTzSdK7LI8y0jBmj0/NGufT9tjwq4DNm6HMyPJxN+Eny1lv4w8PlKadlIulY+j8QkZeis9z5mfNuA17mnPthXpHrJfr78+2BXTYLv9csiKDgR30D3a0sWZK9GOcRZlomToy28PMc9XLGDNiwIdvwG+Wt9dLvbJJa+DjnfgT8KMe49DTBB9La8OPJO586FZ/WDRvgyCPbGxejedoh+NOn1zrUFfW8T54Mu3Zpf5Neej67hURt+CLyXBF5bsz252Qfrd4j+ECahR9P3vnUqfi07t3bW+kuC5MmRbv087bwH300v/Cj8GVz3z4rp51I0k57nwYiRk9manWfkZLgA5nHJ1dlFPxesiCCae2ldJeFdrn09+7NL/worJx2NkkF/3jgjojtd1f3GSnxD2R/v/awzSP83buzny6zaHrdwg//N7qDdrn0PUVb+OH/RmeQVPCfQmfHC3MEYMPqZoB/IPOqFXvB37tXRb8Mgt9LFoRZTt1Nu1z6HrPwDUgu+D8GPi4i/78Iicih6Ex5P84jYr2GfyDzqhV7wc/zBVMEZuH3VrrLQrtc+h6z8A1I3kv//wD/BTwkIndWt50KbAIuziNivUZRFn63C74fphR6y4KYOFG/5z54sLfSXRYmToStW0dvL5tL3yz8zibpd/hDInIasAQ4vbr5q8DXnHO74880klKEhb9vn86pHrxet9HXp3Ns91pvdRFN7/btvZXustArLn2z8DubZr7D3w18Mce49DRFWPgAW7aMXO9G+vtV8HvNgpg8WQW/19JdBnrFpW8WfmeTWPBFZCxwFjAfGB/c55y7PuN49RxFWPhQHsHftq33LAif3l5LdxmwXvpGJ5BI8EXkBOC7wNMAAYar5+4H9gIm+CkxCz85eedVp+LT22vpLgP1XPp+rP2sCVr4wb4veRIcQ8TKaeeRtJf+Z4DVwDRgN3AisBi4HfiTfKLWW5iFn5y886pTMQu/e6ln4ff3ax+NrPEW/oQJ+YztEcXYsbXKRR4DiBnpSOrSfwbwXOfcLhE5CIx1zlVE5G+Az6I99o0UmIWfHLPw2xsPo3kaCX5e15w4sTjr3jN5snotxiQ1J43CSHpLBLXsATajA+4APAI8PetI9SK/+Y3+fvSjsHAhDA5mG35ZBH9wEG67Tf+femr2+dSpDA7CLbfo/4su6p10l4VJk3TK2P37R27PU/AHB/XLnG3b8nmnxF1z2zadQKeoaxrJSWrh3w2cBjwI/C/wfhEZBi4B7s8pbj3D4CB85jO19XXrYOlS/Z/VNJ9lEPzBQc0XbymtX599PnUiPt2+g9ejj/ZGusvExIn6u2cPjBtX256X4Psyc/CgrufxTom75oEDxV3TaI6kFv5y1MoH+BDaU/9nwAuB9+QQr55i2bLaJBee3bt1e1aUQfCXLauJnifrfOpEejXdZcK71cNu/bwEvx1lxspp55N04J0fB/4/CJxYHVp3m3PO5RW5XsHPWZ10eyuEBd9bHN1EEfnUifRqusuEf97CPfXzEvx2lBkrp51Py90qnHOPm9hnw/z5zW1vhaDgT5rUnR1qisinTqRX010mgi79IHkJfjvKjJXTzqcLX/vlY/ny0Q99f79uzwof/s6d3enOh2LyqRPp1XSXiaJd+u0oM1ZOOx8T/A5gyRJYsQIWLNDvcRcs0PUsO7oEH8RuFfwi8qkT6dV0l4miXfrtKDNWTjsfKatXfvHixW7VqlXtjkZHMW6c9qA9/ni49952x8Yweoef/hQuuAB+/nN47nNr2+fMgZe/HL7whbZFzSgZIrLaObc4al/hFr6IXCYia0Vkj4isFpFnNzh+vIhcUT1nr4isFxH7MqAFvCXRrRa+YXQrRbv0DSOKxJPnZIGIXAxcDVwG/E/194cissg5F9eX8+vAkcBSYA0wGyh47Khy0N8PTz5pLxjDKJool75zJvhGsRQq+MD7gOucc36a3XeLyEXApcDl4YNF5IXABcAxzrnqB2U8VEREy4hZ+IbRHqJ66e/fr6Pv2fNoFEVhLn0RGQ+cCdwc2nUz8KyY014B/BZ4n4g8IiJrROSfRMRGE28BE3zDaA9RLv08p8Y1jCiKtPBnAn3AxtD2jcALYs45GjgPnYL3T4Dp6GQ984BXhw8WkaWo65/59vHnKEzwDaM9RLn0TfCNoinapd8sYwAHvM45tx1ARN4F/FhEZjvnRlQenHMrgBWgvfSLjmynY4JvGO0hyqVvgm8UTZG99LcAw2inuyCzgcdizhkCHvViX+X31V8z4ZvEBN8w2oO59I1OoDDBd87tA1YDF4Z2XQj8Kua0XwLzQm32x1V/12Ubw/Jjgm8Y7WH8eP01l77RTor+Dv8q4M0i8nYROVFErkbb4/8FQESuF5HrA8d/DdgKXCsiJ4nIuehnfTc55zYVHPeuxwTfMNqDiLr1zcI32kmhbfjOuRtF5DB0it25wN3Ai51z3lqfHzp+p4i8AO2o91tgG/DvwAeKi3V5MME3jPYxaZIJvtFeCu+055y7BrgmZt/5EdvuA16Yc7R6AhN8w2gfEyeaS99oLzZ5Tg9hgm8Y7cNc+ka7McHvIUzwDaN9TJpkFr7RXkzwe4TBQfjEJ/T/u96l64ZhFMPgIKxZA9/6FixcCJddBsuW6b5nPMOeR6MYOn3gHSMDBgdh6dKaRbF5s66DzVVtGHnjn7/9+3V93Tr4/Odr+x9+2J5HoxjEuXIOSLd48WK3atWqdkejI1i4UF8yYRYsgIceKjo2htFbxD1/Yex5NLJARFY75xZH7TOXfg+wPmbi4bjthmFkR9LnzJ5HI29M8HuAuHmEbH4hw8ifpM+ZPY9G3pjg9wDLl4/uCdzfr9sNw8iXqOcvjD2PRhGY4PcAS5bAihXaRiiivytWWAchwyiCqOfv0kvteTSKxzrtGYZhGEZJsE57hmEYhtHjmOAbhmEYRg9ggm8YhmEYPUBp2/BFZDOQYLiLuswEtmQQnV7H8jE7LC+zw/IyOywvsyNtXi5wzs2K2lFawc8CEVkV1/nBSI7lY3ZYXmaH5WV2WF5mR555aS59wzAMw+gBTPANwzAMowcwwa/PinZHoCRYPmaH5WV2WF5mh+VlduSWl9aGbxiGYRg9gFn4hmEYhtEDmOAbhmEYRg9ggh+BiFwmImtFZI+IrBaRZ7c7Tp2OiFwuIr8VkSdFZLOIfFdETg4dIyLyERHZICJPicjPReSkdsW5G6jmqxORfw5ss3xMiIjMFZGvVsvkHhG5R0SeG9hveZkAEekTkSsD78W1IvL3IjI2cIzlZQQi8hwR+Q8RebT6LL85tL9hvonIDBG5QUS2V5cbRGR6s3ExwQ8hIhcDVwMfBc4AfgX8UERstur6nA9cAzwLeD5wrYp8eQAABUtJREFUAPhPETk0cMzfAH8FvBt4BrAJ+ImITCk2qt2BiJwNLAXuDO2yfExA9YX4S0CAlwAnonm2KXCY5WUy3g+8E3gPcALw3ur65YFjLC+jmQzcjebZUxH7k+Tb14AB4KLqMgDc0HRMnHO2BBbgVuCLoW1rgI+1O27dtFQL+TDw0uq6AEPAssAxk4AdwJ+3O76dtgDTgAeA5wE/B/7Z8rHpPPwo8Ms6+y0vk+fl94CvhrZ9Ffie5WVT+bgTeHNgvWG+oRVVB5wbOOa86rbjm7m+WfgBRGQ8cCZwc2jXzajlaiRnCupB2lZdfxowh0DeOueeAv4Ly9soVgA3Oed+Ftpu+ZicVwC3isiNIrJJRG4XkXeJiFT3W14m53+A54nICQAisgj15P2gut/ysjWS5Ns5aEXhV4Hzfgnsosm8Hdv4kJ5iJtAHbAxt3wi8oPjodDVXA7cDv66uz6n+RuXtEUVFqhsQkUuApwOvj9ht+Zico4HLgE8D/wCcDny2uu+fsbxsho+jlfh7RGQY1Y7lzrlrqvstL1sjSb7NATa7qmkP4JxzIrIpcH4iTPCNzBGRq1CX03nOueF2x6ebEJHjUVf0ec65/e2OT5czBljlnPPtzLeJyLFo2/M/x59mRHAx8EbgdcDv0MrT1SKy1jn35bbGzEiMufRHsgVtd54d2j4beKz46HQfIvJp4LXA851zDwZ2+fyzvK3POain6XcickBEDgDPBS6r/t9aPc7ysTFDwD2hbb8HfAdcK5PJ+QTwSefc151zdznnbgCuotZpz/KyNZLk22PArEBTFNX/h9Nk3prgB3DO7QNWAxeGdl3IyPYTIwIRuZqa2N8b2r0WLZwXBo6fCDwby9sg/w6cglpQflkFfL36/w9YPibll8DxoW3HUZs228pkcvpRYyjIMDUNsbxsjST59mu0E/Q5gfPOAQ6h2bxtd6/FTltQ19U+4O1o78ir0Q4TC9odt05egM8BT6IdeeYElsmBY94PbAdeBZyMitgGYEq749/JC4Fe+paPTeXbM4D9wDK0T8Rrqvn2TsvLpvPyOuAR9PPGhcArgc3ApywvG+bdZGqV993A31b/z0+ab8APgbtQoT+n+v+7Tcel3ZnRiQva0echYC9q8T+n3XHq9AX9RCRq+UjgGAE+grpa9wC/AE5ud9w7fYkQfMvH5Hn3EuCOaj79Af2OXCwvm87HKcBnUO/IU8CDaF+TiZaXDfPu/Jh343VJ8w2YAaxEjaonq/+nNxsXmzzHMAzDMHoAa8M3DMMwjB7ABN8wDMMwegATfMMwDMPoAUzwDcMwDKMHMME3DMMwjB7ABN8wDMMwegATfMMwDMPoAUzwDcPIBBH5BxH5SbvjYRhGNCb4hmFkxenolMiGYXQgJviGYWTF6cBt7Y6EYRjRmOAbhpEaEZmDTul5e3X9EBH5uohURGRhO+NmGIZigm8YRhacjk6qcp+IHA/8L3AAONc591A7I2YYhmKCbxhGFpyOTtn5CnSO7i86517vnHuqvdEyDMNjs+UZhpEaEfk68EKgD3iZc+4XbY6SYRghzMI3DCMLTgf+DRgHHNrmuBiGEYFZ+IZhpEJE+oEdwNnAccAXgOc45yptjZhhGCMY2+4IGIbR9ZwKOOBu59xvReQE4LsicpZz7tE2x80wjCrm0jcMIy2nA2sCHfT+Fvgl8B9V698wjA7AXPqGYRiG0QOYhW8YhmEYPYAJvmEYhmH0ACb4hmEYhtEDmOAbhmEYRg9ggm8YhmEYPYAJvmEYhmH0ACb4hmEYhtEDmOAbhmEYRg9ggm8YhmEYPcD/AzD2iixip/QcAAAAAElFTkSuQmCC\n",
            "text/plain": [
              "<Figure size 576x216 with 1 Axes>"
            ]
          },
          "metadata": {
            "tags": [],
            "needs_background": "light"
          }
        }
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "AhHGJXz6IKqG",
        "outputId": "94c90731-5427-4c01-e135-a59f95ce4ea0"
      },
      "source": [
        "\n",
        "np.mean(accuracy_scores)"
      ],
      "execution_count": 51,
      "outputs": [
        {
          "output_type": "execute_result",
          "data": {
            "text/plain": [
              "0.79461277"
            ]
          },
          "metadata": {
            "tags": []
          },
          "execution_count": 51
        }
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "LoKIeLzeIrm3"
      },
      "source": [
        " "
      ],
      "execution_count": 10,
      "outputs": []
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "AcprAqQMJfQ6"
      },
      "source": [
        ""
      ],
      "execution_count": 12,
      "outputs": []
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "s_WvVLfwLCjv"
      },
      "source": [
        ""
      ],
      "execution_count": null,
      "outputs": []
    }
  ]
}